name: khataman_quran
description: Khataman Quran Tracking App
publish_to: 'none'
version: 1.11.3+28
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.0
  provider: ^6.1.1
  google_sign_in: ^6.1.6
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.2
  flutter_dotenv: ^5.1.0
  quran: ^1.2.4
  share_plus: ^10.1.4
  app_links: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/app_icon.png
    - assets/images/app_icon_dark.png
    - assets/images/adaptive_foreground.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  
  # Adaptive Icon Android (Light / Dark mode & Material You support)
  adaptive_icon_background: "#2ECC71"
  adaptive_icon_background_dark: "#102A1E"
  adaptive_icon_foreground: "assets/images/adaptive_foreground.png"
  adaptive_icon_monochrome: "assets/images/adaptive_foreground.png"
  
  # iOS 18+ Adaptive/Dark/Tinted icon support
  image_path_ios_dark_transparent: "assets/images/adaptive_foreground.png"
  image_path_ios_tinted_grayscale: "assets/images/adaptive_foreground.png"
  desaturate_tinted_to_grayscale_ios: true
  remove_alpha_ios: true

  web:
    generate: true
    image_path: "assets/images/app_icon.png"
