import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/settings_provider.dart';

const Map<String, Map<String, String>> localizedStrings = {
  'id': {
    'title_settings': 'Pengaturan',
    'section_appearance': 'Tampilan',
    'tile_theme': 'Tema Aplikasi',
    'theme_dark': 'Gelap',
    'theme_light': 'Terang',
    'tile_font_size': 'Ukuran Teks',
    'font_size_small': 'Kecil',
    'font_size_normal': 'Normal',
    'font_size_large': 'Besar',
    'section_notifications': 'Notifikasi',
    'tile_reminder': 'Pengingat Khataman',
    'status_active': 'Aktif',
    'status_inactive': 'Nonaktif',
    'tile_reminder_time': 'Jam Pengingat',
    'tile_group_notif': 'Notifikasi Update Grup',
    'subtitle_group_notif': 'Saat anggota klaim atau selesai Juz',
    'section_prayer_azan': 'Shalat & Azan',
    'tile_azan_notif': 'Notifikasi Azan',
    'tile_azan_sound': 'Suara Azan',
    'tile_calc_method': 'Metode Kalkulasi',
    'tile_madhab': 'Madhab',
    'section_reading_target': 'Target Membaca',
    'tile_daily_target': 'Target Harian',
    'text_daily_target_prefix': 'Membaca ',
    'text_daily_target_suffix': ' Juz per hari',
    'section_about': 'Tentang',
    'tile_about_app': 'Tentang Aplikasi',
    'tile_privacy_policy': 'Kebijakan Privasi',
    'subtitle_privacy_policy': 'Cara kami melindungi data Anda',
    'tile_changelog': 'Catatan Perubahan (Changelog)',
    'subtitle_changelog': 'Riwayat pembaruan & versi aplikasi',
    'section_account': 'Akun',
    'tile_delete_account': 'Hapus Akun',
    'subtitle_delete_account': 'Hapus akun dan semua data Anda secara permanen',
    'tile_language': 'Bahasa / Language',
    'dialog_choose_language': 'Pilih Bahasa / Select Language',
    'btn_cancel': 'Batal',
    'btn_save': 'Simpan',
    'btn_close': 'Tutup',
    
    // Sounds
    'sound_default': 'Suara Default Sistem',
    'sound_silent': 'Senyap (Getar Saja)',
    'sound_makkah': 'Azan Makkah',
    'sound_madinah': 'Azan Madinah',

    // Calculation Methods
    'method_kemenag': 'Kemenag RI',
    'method_singapore': 'MUIS Singapura',
    'method_muslim_world_league': 'Liga Dunia Muslim (MWL)',
    'method_egyptian': 'Survei Umum Mesir',
    'method_karachi': 'Universitas Karachi',
    'method_umm_al_qura': 'Umm Al-Qura, Makkah',
    'method_dubai': 'Dubai',
    'method_kuwait': 'Kuwait',
    'method_turkey': 'Diyanet Turki',
    'method_tehran': 'Institut Geofisika Univ. Tehran',

    // Madhabs
    'madhab_syafii': 'Syafi\'i (Standar)',
    'madhab_hanafi': 'Hanafi',
    'madhab_desc_syafii': 'Digunakan di Indonesia, Malaysia, dll.',
    'madhab_desc_hanafi': 'Digunakan di Turki, Pakistan, dll.',

    // About Dialog
    'about_title': 'Tentang Khataman Quran',
    'about_version': 'Versi',
    'about_desc': 'Aplikasi untuk melacak progres Khataman Al-Quran secara mandiri maupun bersama dalam grup.',
    'about_tech_stack': 'Stack Teknologi:',
    
    // Privacy Policy Dialog
    'policy_intro': 'Kami sangat menghargai privasi dan perlindungan data Anda. Aplikasi Khataman Quran dirancang dengan asas transparansi penuh:',
    'policy_1_title': '1. Pengumpulan Data',
    'policy_1_body': 'Aplikasi menyinkronkan data progres membaca Anda (Juz yang diklaim/selesai, riwayat khataman) ke database Supabase Cloud yang aman demi kelancaran akses lintas perangkat Anda.',
    'policy_2_title': '2. Autentikasi Pengguna',
    'policy_2_body': 'Kami menggunakan email Anda (melalui Google Sign-In atau Email Auth) semata-mata untuk keperluan keamanan akun, kepemilikan grup, dan sinkronisasi riwayat Anda.',
    'policy_3_title': '3. Kerahasiaan Penuh',
    'policy_3_body': 'Data pribadi dan progres Anda tidak akan pernah dijual, dibagikan, atau disalahgunakan kepada pihak ketiga mana pun.',
    'policy_4_title': '4. Hak Penghapusan Akun',
    'policy_4_body': 'Anda memiliki hak mutlak untuk menghapus seluruh data Anda kapan saja. Melalui tombol "Hapus Akun", seluruh profil, data grup milik sendiri, riwayat, dan relasi data Anda di database server kami akan dihapus secara instan dan permanen tanpa sisa.',
    'policy_dialog_close': 'Saya Mengerti',

    // Delete Account Dialog
    'delete_confirm_title': 'Hapus Akun?',
    'delete_confirm_body': 'Seluruh data Anda (progres khataman mandiri, riwayat membaca, dan keanggotaan grup) akan dihapus secara PERMANEN.\n\nTindakan ini tidak dapat dibatalkan.',
    'delete_confirm_type_sentence': 'Untuk mengonfirmasi, ketik kalimat di bawah ini:',
    'delete_verify_text': 'iya, saya ingin MENGHAPUS akun ini',
    'delete_verify_hint': 'Ketik kalimat verifikasi di sini...',
    'delete_btn_yes': 'Ya, Hapus',
    'msg_delete_cancelled': 'Hapus akun dibatalkan.',
    'msg_delete_failed': 'Gagal menghapus akun',
    
    // New Admin Dialog
    'dialog_title_new_admin': 'Pilih Admin Baru',
    'dialog_body_new_admin': 'Anda adalah Admin grup "{groupName}". Pilih anggota aktif untuk menggantikan kepemimpinan Anda sebelum akun dihapus:',
    'btn_confirm_continue': 'Konfirmasi & Lanjut',

    // Changelog
    'changelog_title': 'Catatan Perubahan',
    'changelog_v1_13_0_header': 'v1.13.0 (Juni 2026)',
    'changelog_v1_13_0_1': '✨ Loading Shimmer: Transisi loading beranda menggunakan efek Shimmer yang seragam dan elegan.',
    'changelog_v1_13_0_2': '🕋 Kompas Presisi: Ikon Ka\'bah yang dinamis mengelilingi kompas mengikuti ujung jarum kiblat dilengkapi efek getar/haptic.',
    'changelog_v1_13_0_3': '⚡ In-Memory Caching & Offline: Navigasi instan 0ms pada beranda, grup, mandiri, dan jadwal shalat menggunakan cache lokal serta banner peringatan offline.',
    'changelog_v1_13_0_4': '📍 Kustomisasi Lokasi Shalat: Pilihan pencarian manual kota/koordinat dan pembaruan instan waktu shalat.',
    'changelog_v1_13_0_5': '↩️ SnackBar Undo: Tombol "Urungkan" pemulihan database saat menghapus notifikasi satu per satu.',
    
    'changelog_v1_1_0_header': 'v1.1.0 (Mei 2026)',
    'changelog_v1_1_0_1': '✨ Estetika Premium: Penyelarasan tinggi (48px), kebulatan (circular 12), dan pewarnaan cerdas tombol "Saya Sudah Membaca", "Simpan Progres", dan "Lepas" (Light & Dark Mode).',
    'changelog_v1_1_0_2': '👑 Hapus Akun Mandiri & Interaktif: Dukungan transfer kepemimpinan grup (admin) melalui dialog pemilihan anggota secara manual sebelum akun dihapus.',
    'changelog_v1_1_0_3': '🔒 Preservasi Cerdas (Snapshot): Juz yang telah 100% selesai dibaca dipertahankan sebagai snapshot sejarah grup, sedangkan juz inkomplit otomatis dilepas untuk anggota lain.',
    'changelog_v1_1_0_4': '🔔 Pengingat Lintas Platform: Dukungan notifikasi browser Web (HTML5 Notification API) di Chrome serta kueri izin otomatis untuk Android 13+ & iOS.',
    'changelog_v1_1_0_5': '📜 Catatan Perubahan & Privasi: Penambahan dialog Kebijakan Privasi transparan dan menu Changelog interaktif pada halaman pengaturan.',
    
    'changelog_v1_0_0_header': 'v1.0.0 (Awal 2026)',
    'changelog_v1_0_0_1': '📖 Khataman Mandiri: Melacak membaca Al-Quran mandiri Juz 1 - 30 dengan visual progres yang interaktif.',
    'changelog_v1_0_0_2': '👥 Khataman Grup: Bergabung atau membuat grup bersama rekan-rekan untuk mengkhatamkan 30 Juz secara kooperatif.',
    'changelog_v1_0_0_3': '☁️ Supabase Cloud Sync: Sinkronisasi instan dua arah seluruh riwayat dan progres membaca secara real-time.',
    'changelog_v1_0_0_4': '🌗 Tema Dinamis: Dukungan Tema Gelap & Terang yang nyaman bagi mata saat membaca.',

    // Prayer Names
    'prayer_imsak': 'Imsak',
    'prayer_subuh': 'Subuh',
    'prayer_syuruk': 'Syuruk',
    'prayer_dhuha': 'Dhuha',
    'prayer_dzuhur': 'Dzuhur',
    'prayer_ashar': 'Ashar',
    'prayer_maghrib': 'Maghrib',
    'prayer_isya': 'Isya',
    'tile_azan_format': 'Azan {prayer}',
    
    // Add missing targets
    'target_daily_target_juz': 'Membaca {target} per hari',
    'target_1_10': '1/10 Juz (2 Halaman) per hari',
    'target_1_8': '1/8 Juz (2.5 Halaman) per hari',
    'target_1_4': '1/4 Juz (5 Halaman) per hari',
    'target_1_2': '1/2 Juz (10 Halaman) per hari',
    'target_3_4': '3/4 Juz (15 Halaman) per hari',
    'target_1': '1 Juz (20 Halaman) per hari',
    'target_2': '2 Juz (40 Halaman) per hari',
    'target_3': '3 Juz (60 Halaman) per hari',
    'target_4': '4 Juz (80 Halaman) per hari',
    'target_5': '5 Juz (100 Halaman) per hari',

    // Other settings
    'footer_made_with': 'Dibuat dengan ❤️ untuk umat',

    // Home Dashboard
    'home_fallback_name': 'Hamba Allah',
    'home_greeting': 'Assalamu\'alaikum,',
    'home_tooltip_notification': 'Notifikasi',
    'home_tooltip_settings': 'Pengaturan',
    'home_active_khataman': 'Khataman Aktif Anda',
    'home_btn_quick_update': 'Update Cepat Progres Bacaan',
    'home_empty_slot_title': 'Slot Tersedia',
    'home_empty_slot_desc': 'Mulai program khataman baru',
    'home_show_less': 'Tampilkan Lebih Sedikit',
    'home_show_more': 'Tampilkan Lebih Banyak',
    'home_type_group': 'Grup',
    'home_type_mandiri': 'Mandiri',
    'home_start_now': 'Mulai Sekarang',
    'home_feat_mushaf_title': 'Mushaf Al-Quran',
    'home_feat_mushaf_subtitle': 'Baca Al-Quran offline dengan terjemahan Indonesia',
    'home_feat_mandiri_title': 'Khataman Mandiri',
    'home_feat_mandiri_subtitle': 'Lacak progres membaca Al-Quran pribadi Anda',
    'home_feat_group_title': 'Khataman Grup',
    'home_feat_group_subtitle': 'Khataman Al-Quran bersama anggota grup',
    'home_feat_prayer_title': 'Jadwal Shalat',
    'home_feat_prayer_subtitle': 'Waktu shalat, countdown, & notifikasi azan',
    'home_feat_qibla_title': 'Arah Kiblat',
    'home_feat_qibla_subtitle': 'Kompas digital penunjuk arah Ka\'bah',
    'home_stat_total_juz': 'Total Juz',
    'home_stat_surah': 'Surah',
    'home_stat_ayat': 'Ayat',
    'home_history_header': '🏆  RIWAYAT & STATISTIK SAYA',
    'home_history_title_completed': 'Alhamdulillah, {count} Kali Khatam Al-Quran',
    'home_history_title_empty': 'Pantau Progres & Statistik Khataman Anda',
    'home_history_subtitle': 'Lihat riwayat membaca minggu ini, bulan ini, & tahun ini ➔',
    'home_join_group_not_found': 'Grup dengan kode "{code}" tidak ditemukan.',
    'home_join_group_pending': 'Permintaan Anda bergabung di "{groupName}" masih PENDING persetujuan Admin.',
    'home_join_group_rejected': 'Keanggotaan Anda di "{groupName}" ditolak/ditangguhkan.',
    'home_join_group_failed_link': 'Gagal memproses link: {error}',
    'home_join_dialog_title': 'Gabung Grup',
    'home_join_dialog_body': 'Apakah Anda ingin mengajukan bergabung ke grup "{groupName}" (Kode: {code})?',
    'home_join_dialog_cancel': 'Batal',
    'home_join_dialog_confirm': 'Gabung',
    'home_join_sent_pending': 'Permintaan bergabung terkirim! Tunggu persetujuan Admin.',
    'home_join_success': 'Berhasil bergabung dengan "{groupName}"!',
    'home_join_failed': 'Gagal bergabung: {error}',
    'home_notif_new': 'Notifikasi Baru',
    'home_notif_silent_title': 'Notifikasi Grup (Hening)',
    'home_notif_default_title': 'Notifikasi Grup (Suara)',
    'home_notif_silent_desc': 'Notifikasi grup tanpa suara untuk menghindari overlap waktu shalat',
    'home_notif_default_desc': 'Notifikasi grup dengan suara bawaan',

    // Mandiri Screen
    'mandiri_max_ayat_error': 'Nomor ayat melebihi batas maksimal (Max: {total})',
    'mandiri_log_juz_completed': 'Alhamdulillah, telah menyelesaikan Juz {juz}!',
    'mandiri_save_failed': 'Gagal menyimpan: {error}',
    'mandiri_reset_dialog_title': 'Mulai Khatam Baru?',
    'mandiri_reset_dialog_body': 'Progress bacaan saat ini akan dimulai kembali dari awal. Riwayat khatam sebelumnya tetap tersimpan.',
    'mandiri_reset_dialog_cancel': 'Batal',
    'mandiri_reset_dialog_confirm': 'Mulai Baru',
    'mandiri_reset_success': 'Progres berhasil direset. Bismillah, mulai lagi! 🌙',
    'mandiri_reset_failed': 'Gagal reset: {error}',
    'mandiri_confirm_khatam_title': 'Konfirmasi Khataman',
    'mandiri_confirm_khatam_body': 'Apakah Anda sudah selesai membaca Doa Khatam Al-Quran?\n\nJika sudah, progres khataman akan dicatat ke dalam riwayat dan di-reset kembali ke Juz 1.',
    'mandiri_confirm_khatam_instruction': 'Tindakan ini akan mencatat khataman Mandiri Anda ke riwayat, lalu mereset seluruh progres kembali ke Juz 1 untuk memulai putaran baru. Lanjutkan?',
    'mandiri_btn_read_doa': 'Belum, Baca Doa',
    'mandiri_btn_yes_done': 'Ya, Sudah',
    'mandiri_log_khatam_completed': '🏆 Menyelesaikan Khataman Mandiri 30 Juz! Alhamdulillah!',
    'mandiri_khatam_logged': '🏆 Khataman berhasil dicatat! Bismillah, mulai lagi!',
    'mandiri_khatam_failed': 'Gagal mencatat khataman: {error}',
    'mandiri_title': 'Khataman Mandiri',
    'mandiri_tooltip_reset': 'Reset Semua Progres',
    'mandiri_btn_reset_khatam': 'Mulai Khataman Baru',
    'mandiri_progress_title': 'Progres Khataman',
    'mandiri_juz_completed_count': '{completed} / 30 Juz Selesai',
    'mandiri_progress_short': 'Progres Mandiri: {completed}/30 Juz',
    'mandiri_offline_banner': 'Koneksi Terputus. Menampilkan data offline terakhir.',

    // Doa Khatam Component
    'doa_title': 'Doa Khatam Al-Quran',
    'doa_transliteration_header': 'Transliterasi:',
    'doa_translation_header': 'Arti / Terjemahan:',
    'doa_translation_text': '“Ya Allah, rahmatilah aku dengan Al-Quran. Jadikanlah ia bagiku sebagai pemimpin, cahaya, petunjuk, dan rahmat. Ya Allah, ingatkanlah aku atas apa yang terlupakan darinya, ajarilah aku atas apa yang belum aku ketahui darinya, dan berikanlah aku rezeki untuk membacanya di malam hari dan ujung-ujung siang. Dan jadikanlah ia bagiku sebagai pembela, wahai Tuhan semesta alam.”',
    'doa_confirm_complete_title': 'Selesaikan Khataman?',
    'doa_confirm_complete_body': 'Tindakan ini akan mencatat khataman ke riwayat dan menyelesaikan progres putaran saat ini. Lanjutkan?',
    'doa_btn_yes_complete': 'Ya, Selesaikan',
    'doa_btn_read_already': 'Saya Telah Membaca Doa',
    'congrats_title': 'Maa Syaa Allah, Barakallah! 🎉',
    'congrats_desc': 'Selamat! Anda telah menyelesaikan khataman 30 Juz Al-Quran.',
    'congrats_btn_reset': 'Reset Progres',
    'congrats_btn_doa': 'Doa Khatam',

    // Qibla Screen
    'qibla_loading_location': 'Memuat lokasi...',
    'qibla_fallback_location': 'Lokasi Anda',
    'qibla_title': 'Arah Kiblat',
    'qibla_distance_suffix': 'km ke Ka\'bah',
    'qibla_active_compass': 'Kompas Merespons',
    'qibla_aligned': 'Anda Menghadap Kiblat! ✅',
    'qibla_turn_device': 'Putar perangkat Anda menuju Ka\'bah',
    'qibla_offset_text': '{offset}° offset dari posisi Anda',
    'qibla_calibration_tip': 'Tips: Gerakkan HP membentuk angka 8 untuk kalibrasi sensor kompas.',
    'qibla_sensor_unavailable': 'Sensor Tidak Tersedia',
    'qibla_sensor_fallback': 'Perangkat Anda tidak memiliki sensor magnetometer. Menampilkan arah kiblat statis.',
    'qibla_location_unavailable': 'Lokasi tidak tersedia.\nBuka halaman Jadwal Shalat terlebih dahulu untuk mendeteksi lokasi.',
    'qibla_static_heading': 'Arah Kiblat: {bearing}° dari Utara',
    'qibla_static_distance': 'Jarak ke Ka\'bah: {distance} km',
    'qibla_static_from': 'Dari: {location}',

    // Prayer Time Screen
    'prayer_title': 'Jadwal Shalat',
    'prayer_tooltip_settings': 'Pengaturan Kalkulasi',
    'prayer_btn_refresh': 'Refresh',
    'prayer_next_prayer': 'Waktu Shalat Berikutnya',
    'prayer_all_done': 'Semua Shalat Hari Ini Selesai',
    'prayer_at_time': 'pukul {time}',
    'prayer_alhamdulillah': 'Alhamdulillah 🤲',
    'prayer_fard_badge': 'WAJIB',
    'prayer_method_madhab_info': 'Metode: {method} • Madhab: {madhab}',
    'prayer_err_general': 'Terjadi kesalahan',
    'prayer_btn_retry': 'Coba Lagi',
    'prayer_err_enter_city': 'Masukkan nama kota terlebih dahulu',
    'prayer_err_no_internet': 'Tidak ada koneksi internet',
    'prayer_err_city_not_found': 'Kota "{query}" tidak ditemukan',
    'prayer_success_city_changed': 'Lokasi diubah ke: {resolvedName}',
    'prayer_err_failed_search': 'Gagal mencari lokasi. Pastikan ejaan benar.',
    'prayer_settings_title': 'Pengaturan Jadwal & Azan',
    'prayer_settings_loc_section': 'Pengaturan Lokasi',
    'prayer_settings_use_gps': 'Gunakan GPS Otomatis',
    'prayer_settings_use_gps_sub': 'Mencari lokasi berdasarkan posisi perangkat secara real-time',
    'prayer_settings_city_hint': 'Masukkan nama kota (misal: Bandung)',
    'prayer_settings_active_loc': 'Lokasi aktif: {city}',
    'prayer_settings_calc_title': 'Metode Kalkulasi',
    'prayer_settings_madhab_title': 'Madhab (Penentuan Waktu Ashar)',
    'prayer_settings_azan_alarm': 'Notifikasi Alarm Azan',
    'prayer_settings_azan_reminder_time': 'Waktu Shalat yang Diingatkan:',
    'prayer_settings_azan_sound_selection': 'Pilihan Suara Azan',
    'prayer_settings_btn_save': 'Simpan & Terapkan',
    'prayer_offline_banner': 'Koneksi Terputus. Menampilkan data offline terakhir.',
    'prayer_unknown_location': 'Lokasi Tidak Diketahui',
    'prayer_saved_location': 'Lokasi Tersimpan',
    'prayer_default_location': 'Jakarta, Indonesia (Default)',
    'day_monday': 'Senin',
    'day_tuesday': 'Selasa',
    'day_wednesday': 'Rabu',
    'day_thursday': 'Kamis',
    'day_friday': 'Jumat',
    'day_saturday': 'Sabtu',
    'day_sunday': 'Ahad',
    'month_january': 'Januari',
    'month_february': 'Februari',
    'month_march': 'Maret',
    'month_april': 'April',
    'month_may': 'Mei',
    'month_june': 'Juni',
    'month_july': 'Juli',
    'month_august': 'Agustus',
    'month_september': 'September',
    'month_october': 'Oktober',
    'month_november': 'November',
    'month_december': 'Desember',

    // Profile Screen
    'profile_err_empty_username': 'Username tidak boleh kosong',
    'profile_err_min_char': 'Username minimal 3 karakter',
    'profile_err_invalid_char': 'Username hanya boleh huruf, angka, titik (.), dan underscore (_)',
    'profile_success_username_changed': 'Username berhasil diubah!',
    'profile_err_username_taken': 'Username sudah dipakai orang lain, coba yang lain',
    'profile_confirm_logout_title': 'Keluar?',
    'profile_confirm_logout_body': 'Anda akan keluar dari akun ini.',
    'profile_confirm_logout_yes': 'Ya, Keluar',
    'profile_title': 'Profil Saya',
    'profile_fallback_username': 'Pengguna',
    'profile_username_rules': 'Aturan Username:\n• Minimal 3 karakter\n• Hanya huruf (a-z), angka (0-9), titik (.), & underscore (_)',
    'profile_btn_edit': 'Ubah',
    'profile_hint_new_username': 'Masukkan username baru',
    'profile_rule_min_char': 'Minimal 3 karakter',
    'profile_rule_valid_char': 'Hanya huruf, angka, titik (.), dan underscore (_)',
    'profile_tile_email': 'Email',
    'profile_tile_login_with': 'Login dengan',
    'profile_tile_joined_since': 'Bergabung sejak',
    'profile_btn_logout': 'Keluar dari Akun',
    'month_jan_short': 'Jan',
    'month_feb_short': 'Feb',
    'month_mar_short': 'Mar',
    'month_apr_short': 'Apr',
    'month_may_short': 'Mei',
    'month_jun_short': 'Jun',
    'month_jul_short': 'Jul',
    'month_aug_short': 'Ags',
    'month_sep_short': 'Sep',
    'month_oct_short': 'Okt',
    'month_nov_short': 'Nov',
    'month_dec_short': 'Des',

    // History Screen
    'history_cycle_title_mandiri': 'Khataman Mandiri',
    'history_cycle_desc_mandiri': '🏆 Khataman Mandiri 30 Juz!',
    'history_cycle_title_group': 'Khataman Grup "{groupName}"',
    'history_cycle_desc_group': '🏆 Khataman Grup bersama "{groupName}"! Kontribusi {count} Juz.',
    'history_cycle_group_fallback': 'Grup',
    'history_info_tooltip': 'Jumlah total penyelesaian Khataman Al-Quran Anda, gabungan dari Khataman Mandiri dan kontribusi Khataman Grup.',
    'history_confirm_clear_title': 'Hapus Seluruh Riwayat?',
    'history_confirm_clear_body': 'Semua catatan aktivitas membaca dan statistik khatam personal Anda akan dihapus secara permanen.\n\nTindakan ini tidak dapat dibatalkan.',
    'history_confirm_clear_yes': 'Ya, Hapus Semua',
    'history_clear_success': 'Seluruh riwayat personal Anda telah dibersihkan.',
    'history_time_just_now': 'Baru saja',
    'history_time_minutes_ago': '{minutes} menit yang lalu',
    'history_time_hours_ago': '{hours} jam yang lalu',
    'history_time_yesterday': 'Kemarin, {time}',
    'history_title': 'Riwayat & Statistik Saya',
    'history_stat_title_total': 'TOTAL KHATAM AL-QURAN',
    'history_stat_count_suffix': 'Kali',
    'history_stat_khatam_label': 'Khatam 30 Juz',
    'history_section_my_stats': 'Statistik Membaca Saya',
    'history_stat_week': 'Minggu Ini',
    'history_stat_month': 'Bulan Ini',
    'history_stat_year': 'Tahun Ini',
    'history_stat_juz_completed': 'Juz Selesai',
    'history_section_log_title': 'Catatan Riwayat Aktivitas',
    'history_section_log_count': '{count} Khataman',
    'history_empty_title': 'Mulai Membaca Al-Quran',
    'history_empty_body': 'Simpan progres membaca Anda di Khataman Mandiri atau Khataman Grup untuk melihat histori membaca Anda di sini.',
    'history_detail_read_juz': 'Rincian Juz yang Dibaca:',
    'history_detail_no_juz': 'Tidak ada detail juz terekam.',

    // Notifications Screen
    'notif_request_processed': 'Permintaan telah diproses',
    'notif_join_approved_msg': 'Permintaan bergabung berhasil disetujui',
    'notif_join_approve_failed': 'Gagal menyetujui permintaan: {error}',
    'notif_reject_confirm_title': 'Tolak Permintaan?',
    'notif_reject_confirm_body': 'Apakah Anda yakin ingin menolak permintaan bergabung ini?',
    'notif_reject_btn_confirm': 'Tolak',
    'notif_join_rejected_msg': 'Permintaan bergabung berhasil ditolak',
    'notif_join_reject_failed': 'Gagal menolak permintaan: {error}',
    'notif_release_approved_msg': 'Pengajuan lepas Juz berhasil disetujui',
    'notif_release_approve_failed': 'Gagal menyetujui pelepasan: {error}',
    'notif_release_reject_title': 'Tolak Pengajuan?',
    'notif_release_reject_body': 'Apakah Anda yakin ingin menolak pengajuan pelepasan Juz {juz} ini?',
    'notif_release_rejected_msg': 'Pengajuan lepas Juz berhasil ditolak',
    'notif_release_reject_failed': 'Gagal menolak pelepasan: {error}',
    'notif_mark_all_read_msg': 'Semua notifikasi telah ditandai dibaca',
    'notif_delete_success': 'Notifikasi berhasil dihapus 🗑️',
    'notif_undo_label': 'URUNGKAN',
    'notif_undo_failed': 'Gagal mengurungkan penghapusan: {error}',
    'notif_delete_failed': 'Gagal menghapus notifikasi: {error}',
    'notif_clear_all_title': 'Hapus Semua Notifikasi?',
    'notif_clear_all_body': 'Apakah Anda yakin ingin menghapus seluruh riwayat notifikasi Anda? Tindakan ini tidak dapat dibatalkan.',
    'notif_clear_all_confirm': 'Hapus Semua',
    'notif_clear_all_success': 'Seluruh notifikasi berhasil dibersihkan',
    'notif_clear_all_failed': 'Gagal menghapus semua notifikasi: {error}',
    'notif_title': 'Notifikasi',
    'notif_btn_mark_read': 'Tandai semua dibaca',
    'notif_btn_clear_all': 'Hapus semua notifikasi',
    'notif_badge_processed': 'Permintaan telah diproses',
    'notif_badge_approved': 'Berhasil Disetujui',
    'notif_badge_rejected': 'Berhasil Ditolak',
    'notif_badge_cancelled_label': 'Permintaan dibatalkan',
    'notif_badge_rejected_label': 'Permintaan ditolak',
    'notif_badge_approved_label': 'Permintaan disetujui',
    'notif_badge_release_approved_label': 'Pengajuan lepas Juz disetujui',
    'notif_badge_release_rejected_label': 'Pengajuan lepas Juz ditolak',
    'notif_btn_approve_action': 'Setujui',
    'notif_btn_reject_action': 'Tolak',
    'notif_empty_title': 'Belum Ada Notifikasi',
    'notif_empty_body': 'Aktivitas grup Anda akan muncul di sini.',
    'notif_join_cancelled_title': 'Permintaan Dibatalkan',
    'notif_time_just_now': 'Baru saja',
    'notif_time_minutes_ago': '{minutes} menit yang lalu',
    'notif_time_hours_ago': '{hours} jam yang lalu',
    'notif_time_days_ago': '{days} hari yang lalu',
    
    // Mushaf Screen
    'mushaf_title': 'Mushaf Al-Quran',
    'mushaf_tab_surah': 'Surah',
    'mushaf_tab_juz': 'Juz',
    'mushaf_last_read_header': 'Terakhir Dibaca',
    'mushaf_last_read_surah_ayat': 'Surah {surah} (Ayat {ayat})',
    'mushaf_last_read_juz': 'Juz {juz}',
    'mushaf_last_read_continue': 'Lanjutkan',
    'mushaf_search_hint': 'Cari surah (contoh: Yasin, Al-Mulk...)',
    'mushaf_makkiyah': 'Makkiyah',
    'mushaf_madaniyah': 'Madaniyah',
    'mushaf_verses_count': '{count} Ayat',
    'mushaf_juz_detail_single': 'Surah {surah} (Ayat {start}-{end})',
    'mushaf_juz_detail_multi': 'Surah {start} ke {end}',
    'mushaf_empty_search': 'Surah tidak ditemukan',

    // Mushaf Reader Screen
    'mushaf_reader_bookmark_saved': 'Penanda buku disimpan: Surah {surah} ayat {ayat}',
    'mushaf_reader_err_reverse': 'Anda telah membaca ayat ini.',
    'mushaf_reader_log_juz_completed_mushaf': 'Alhamdulillah, telah menyelesaikan Juz {juz} melalui Mushaf!',
    'mushaf_reader_notif_completed_title': 'Juz Selesai Dibaca',
    'mushaf_reader_notif_completed_body': '{user} telah menyelesaikan Juz {juz} di grup "{group}" melalui Mushaf',
    'mushaf_reader_success_completed': '✅ Juz {juz} selesai! Progres khataman berhasil disinkronkan!',
    'mushaf_reader_success_saved': 'Progres berhasil disimpan!',
    'mushaf_reader_err_save': 'Gagal menyimpan progres: {error}',
    'mushaf_reader_settings_title': 'Pengaturan Tampilan',
    'mushaf_reader_arabic_text_size': 'Ukuran Teks Arab',
    'mushaf_reader_translation_text_size': 'Ukuran Terjemahan',
    'mushaf_reader_show_translation': 'Tampilkan Terjemahan',
    'mushaf_reader_selected_verse_title': 'Ayat Terpilih',
    'mushaf_reader_bookmark_label': 'Bookmark',
    'mushaf_reader_juz_progress_text': 'Juz {juz} • Progres: {current} / {total} Ayat ({percent}%)',
    'mushaf_reader_mark_juz_done': 'Tandai Selesai Juz',
    'mushaf_reader_progress_new_label': 'Pilih Progres Baru s.d:',
    'mushaf_reader_save_progress_label': 'Simpan Progres',
    'mushaf_reader_juz_completed_banner': '✨ Alhamdulillah, Juz ini telah selesai dibaca!',
    'mushaf_reader_tap_instruction_banner': '💡 Ketuk ayat terakhir yang Anda baca untuk memperbarui progres.',
    'mushaf_reader_no_program_title': 'Tidak ada program aktif untuk Juz {juz}',
    'mushaf_reader_no_program_desc': 'Mulai khataman mandiri atau cari grup untuk melacak progres membaca Juz ini.',
    'mushaf_reader_btn_start_mandiri': 'Mulai Mandiri',
    'mushaf_reader_btn_find_group': 'Cari Grup',
    'mushaf_reader_switch_program_label': 'Pilih Program:',
    'mushaf_reader_btn_select_verse': 'Pilih Ayat',
    'mushaf_reader_dialog_select_verse_title': 'Pilih Ayat Progres',
    'mushaf_reader_select_verse_tip': 'Tip: Anda juga bisa langsung mengetuk teks ayat mana saja di atas untuk memilih.',
    'mushaf_reader_btn_apply': 'Terapkan',

    // Surah Info Screen
    'surah_info_title': 'Info & Makna Surah',
    'surah_info_search_hint': 'Cari surah (contoh: Al-Fatihah, Pembukaan...)',
    'surah_info_empty_search': 'Surah tidak ditemukan',

    // Surah Detail Screen
    'surah_detail_juz_place_verses': 'Surah Ke-{number} • {place} • {verses} Ayat',
    'surah_detail_translation_label': 'Arti: {translation}',
    'surah_detail_tab_meaning': 'Arti & Makna',
    'surah_detail_tab_asbabun': 'Hadis & Asbabun Nuzul',
    'surah_detail_tab_asbabun_sub': 'Mengapa surah ini diturunkan',
    'surah_detail_tab_virtue': 'Dampak & Keutamaan',
    'surah_detail_tab_virtue_sub': 'Manfaat & faedah pengamalan',

    // Active Khataman List Screen
    'active_list_title': 'Khataman Aktif Anda',
    'active_list_empty_title': 'Belum Ada Khataman Aktif',
    'active_list_empty_body': 'Silakan buat khataman mandiri atau bergabung dengan grup khataman terlebih dahulu.',

    // Auth Screen
    'auth_login_failed': 'Login Gagal: {error}',
    'auth_title': 'Khataman Quran',
    'auth_tagline': 'Lacak perjalanan spiritual Anda\nbersama atau sendiri.',
    'auth_privacy_notice': 'Dengan masuk, Anda menyetujui Ketentuan Layanan\ndan Kebijakan Privasi kami.',
    'auth_btn_login': 'Masuk dengan Google',
    'auth_tooltip_light_mode': 'Mode Terang',
    'auth_tooltip_dark_mode': 'Mode Gelap',

    // Additional Mandiri Screen keys (UI labels)
    'mandiri_appbar_title': 'Progres Mandiri',
    'mandiri_header_title': 'Progres Khataman',
    'mandiri_header_subtitle': 'Tap juz untuk menandai selesai dibaca',
    'mandiri_juz_label': 'Juz',
    'mandiri_completed_label': 'Selesai',
    'mandiri_not_read_label': 'Belum Dibaca',
    // Group List & Detail & Assignment Screens
    'group_err_load': 'Gagal memuat data: {error}',
    'group_err_empty_name': 'Nama grup tidak boleh kosong',
    'group_success_create': 'Grup "{groupName}" berhasil dibuat! Kode: {code}',
    'group_err_create': 'Gagal membuat grup: {error}',
    'group_invite_title': 'Undang Anggota',
    'group_invite_subtitle': 'Pilih teman untuk diajak mengaji bersama',
    'group_search_user_hint': 'Cari username atau email...',
    'group_no_users': 'Tidak ada pengguna lain',
    'group_no_match_users': 'Tidak ada hasil cocok',
    'group_btn_skip': 'Lewati',
    'group_success_add_members': '{count} anggota berhasil ditambahkan!',
    'group_err_add_members_title': 'Gagal Menambahkan',
    'group_err_add_members_continue': 'Lanjutkan ke Grup',
    'group_err_add_members_body': 'Supabase Error: {error}\n\nKemungkinan besar database (Row Level Security) melarang Anda menambahkan akun orang lain secara langsung.',
    'group_badge_admin': 'Admin',
    'group_empty_my_groups': 'Anda belum bergabung ke grup manapun.\nCari grup di tab "Semua Grup" dan klik Gabung!',
    'group_empty_archived_groups': 'Belum ada grup yang diarsipkan.\nGrup akan diarsipkan setelah Doa Khatam Al-Quran selesai dibaca.',
    'group_btn_add': 'Tambahkan',
    'group_btn_add_count': 'Tambahkan ({count})',
    'group_someone': 'Seseorang',
    'group_notif_join_request_title': 'Permintaan Bergabung',
    'group_notif_join_request_body': '{user} meminta bergabung ke grup "{groupName}"',
    'group_notif_joined_title': 'Anggota Baru Bergabung',
    'group_notif_joined_body': '{user} telah bergabung ke grup "{groupName}"',
    'group_join_pending': 'Permintaan bergabung terkirim! Tunggu persetujuan Admin.',
    'group_join_success': 'Berhasil bergabung dengan "{groupName}"!',
    'group_join_failed': 'Gagal bergabung: sudah terdaftar atau terjadi error',
    'group_join_cancel_success': 'Permintaan bergabung ke "{groupName}" berhasil dibatalkan.',
    'group_join_cancel_failed': 'Gagal membatalkan permintaan: {error}',
    'group_join_cancel_dialog_title': 'Batalkan Permintaan?',
    'group_join_cancel_dialog_body': 'Apakah Anda yakin ingin membatalkan permintaan bergabung dengan grup "{groupName}"?',
    'group_join_cancel_dialog_btn': 'Batalkan Permintaan',
    'group_tab_all': 'Semua Grup ({count})',
    'group_tab_my': 'Grup Saya ({count})',
    'group_tab_archived': 'Arsip ({count})',
    'group_btn_create': 'Buat Grup',
    'group_create_dialog_title': 'Buat Grup Baru',
    'group_create_dialog_subtitle': 'Khataman Al-Quran bersama',
    'group_create_field_name': 'Nama Grup',
    'group_create_field_name_hint': 'Contoh: Khataman Keluarga',
    'group_create_field_visibility': 'Visibilitas Grup',
    'group_create_visibility_public': 'Publik',
    'group_create_visibility_private': 'Privat',
    'group_create_visibility_private_desc': 'Anggota harus disetujui Admin sebelum bergabung.',
    'group_create_field_type': 'Tipe Grup',
    'group_create_type_insidental': 'Insidental',
    'group_create_type_rutin': 'Rutin',
    'group_create_type_rutin_desc': 'Tipe Rutin: Sistem siklus rolling Juz otomatis berputar setelah khatam.',
    'group_create_type_insidental_desc': 'Tipe Insidental: Jatah Juz di-reset total secara manual setelah khatam.',
    'group_create_btn_submit': 'Buat Grup Sekarang',
    'group_search_hint': 'Cari grup atau kode...',
    'group_empty_search': 'Tidak ada grup ditemukan',
    'group_badge_waiting': 'Menunggu',
    'group_badge_join': 'Gabung',
    'group_badge_open': 'Buka',
    'group_admin_label': 'Admin: ',
    'group_admin_you': 'Anda',
    'group_progress_title': 'Progres Grup',
    'group_progress_claimed': '{count} Diambil',
    'group_progress_completed': '{count} Selesai ({percent}%)',
    'group_members_title': 'Anggota Grup ',
    'group_members_count': '{count} Orang',
    'group_members_empty': 'Belum ada anggota.',
    'group_detail_out_by_admin': 'Anda telah dikeluarkan dari grup "{groupName}" oleh admin.',
    'group_detail_celebration_title': 'Maa Syaa Allah! 🎉',
    'group_detail_celebration_alhamdulillah': 'Alhamdulillah',
    'group_detail_dialog_title_period': 'Pilih Periode Khataman',
    'group_detail_btn_select': 'Pilih',
    'group_detail_btn_save': 'Simpan',
    'group_detail_err_roll_juz': 'Rolling Juz gagal: {error}. Slot dibuat kosong.',
    'group_detail_notif_new_cycle_title': '📖 Putaran Baru Dimulai!',
    'group_detail_notif_new_cycle_body': '{admin} memulai putaran baru di grup "{groupName}" dengan tenggat waktu {date}.',
    'group_detail_start_new_cycle_title': 'Mulai Putaran Baru?',
    'group_detail_roll_method_title': 'Rolling Juz',
    'group_detail_roll_method_desc': 'Grup Anda telah menyelesaikan siklus khataman ini.\n\nSilakan pilih metode pembagian Juz untuk putaran berikutnya:',
    'group_detail_roll_method_equal': 'Bagi Rata',
    'group_detail_roll_method_manual': 'Bagi Manual',
    'group_detail_roll_method_claim': 'Klaim Mandiri',
    'group_detail_err_slot_claimed': '⚠️ Juz ini sudah diambil anggota lain. Pilih Juz lain.',
    'group_detail_success_slot_claimed': '✅ Juz berhasil diambil!',
    'group_detail_err_claim_failed': 'Gagal mengambil Juz: {error}',
    'group_detail_direct_released_title': 'Juz Dilepas oleh Admin 🚪',
    'group_detail_direct_released_body': '{user} telah melepas kembali Juz {juz} di grup "{groupName}". Sekarang slot ini kosong dan bebas diambil!',
    'group_detail_direct_released_success': '✅ Juz berhasil dilepas secara langsung dan notifikasi telah dikirim ke anggota.',
    'group_detail_err_max_releases': '⚠️ Maks 2 pengajuan lepas Juz bersamaan. Tunggu admin merespons.',
    'group_detail_release_req_title': 'Pengajuan Pelepasan Juz 📖',
    'group_detail_release_req_body': '{user} mengajukan pelepasan Juz {juz} di grup "{groupName}".',
    'group_detail_release_req_sent': '📤 Pengajuan lepas Juz dikirim. Menunggu persetujuan admin.',
    'group_detail_release_req_failed': 'Gagal mengajukan lepas Juz: {error}',
    'group_detail_release_req_cancelled': '↩️ Pengajuan lepas Juz dibatalkan.',
    'group_detail_release_cancel_failed': 'Gagal membatalkan pengajuan: {error}',
    'group_detail_days_remaining': '{count} hari tersisa',
    'group_detail_hours_remaining': '{count} jam tersisa',
    'group_detail_minutes_remaining': '{count} menit tersisa',
    'group_detail_seconds_remaining': 'Beberapa detik tersisa',
    'group_detail_time_expired': 'Waktu habis',
    'group_detail_add_member_title': 'Tambah Anggota Baru',
    'group_detail_manage_member_title': 'Kelola Anggota',
    'group_detail_add_member_subtitle': 'Cari dan tambahkan anggota baru ke grup',
    'group_detail_manage_member_subtitle': 'Tambah anggota baru atau kelola anggota saat ini',
    'group_detail_search_member_hint': 'Cari username untuk ditambahkan...',
    'group_detail_notif_added_title': 'Ditambahkan ke Grup Khataman',
    'group_detail_notif_added_body': 'Anda telah ditambahkan ke grup "{groupName}" oleh admin.',
    'group_detail_success_added_member': '{user} berhasil ditambahkan ke grup',
    'group_detail_err_added_member': 'Gagal menambahkan: {error}',
    'group_detail_search_empty_members': 'Pengguna tidak ditemukan atau sudah bergabung.',
    'group_detail_search_start_prompt': 'Mulai cari username untuk ditambahkan...',
    'group_detail_current_members_title': 'Daftar Anggota Saat Ini',
    'group_detail_no_other_members': 'Belum ada anggota lain di grup ini.',
    'group_detail_status_pending': 'Menunggu Persetujuan',
    'group_detail_status_active': 'Anggota Aktif',
    'group_detail_btn_approve': 'Terima',
    'group_detail_notif_approved_title': 'Permintaan Bergabung Disetujui',
    'group_detail_notif_approved_body': 'Selamat! Permintaan Anda bergabung ke grup "{groupName}" telah disetujui.',
    'group_detail_success_approved': '{user} berhasil disetujui bergabung',
    'group_detail_err_approved': 'Gagal menyetujui: Koneksi bermasalah atau coba lagi ({error})',
    'group_detail_btn_reject': 'Tolak',
    'group_detail_reject_dialog_title': 'Tolak Permintaan?',
    'group_detail_reject_dialog_body': 'Apakah Anda yakin ingin menolak permintaan bergabung dari {user}?',
    'group_detail_success_rejected': 'Permintaan bergabung {user} ditolak',
    'group_detail_err_rejected': 'Gagal menolak permintaan: Koneksi bermasalah atau coba lagi ({error})',
    'group_detail_priority_title': 'Prioritas Jatah Kuota',
    'group_detail_priority_enabled': '⭐ {user} mendapat prioritas jatah kuota!',
    'group_detail_priority_disabled': '⚪ Prioritas jatah {user} dinonaktifkan.',
    'group_detail_priority_failed': 'Gagal mengubah prioritas: {error}',
    'group_detail_transfer_title': 'Transfer Admin',
    'group_detail_transfer_dialog_title': 'Transfer Admin?',
    'group_detail_transfer_dialog_body': 'Apakah Anda yakin ingin menyerahkan kepemilikan admin kepada {user}?',
    'group_detail_transfer_confirm': 'Ya, Transfer',
    'group_detail_notif_transfer_title': 'Promosi Admin 👑',
    'group_detail_notif_transfer_body': 'Anda telah dijadikan Admin baru untuk grup "{groupName}" oleh admin sebelumnya.',
    'group_detail_success_transfer': 'Hak admin berhasil ditransfer ke {user}',
    'group_detail_err_transfer': 'Gagal mentransfer admin: {error}',
    'group_detail_kick_title': 'Keluarkan Anggota',
    'group_detail_kick_dialog_title': 'Keluarkan Anggota?',
    'group_detail_kick_dialog_body': 'Apakah Anda yakin ingin mengeluarkan {user} dari grup? Semua slot yang dipegang yang bersangkutan akan dikosongkan kembali.',
    'group_detail_kick_confirm': 'Keluarkan',
    'group_detail_notif_kicked_title': 'Dikeluarkan dari Grup 🚪',
    'group_detail_notif_kicked_body': 'Anda telah dikeluarkan dari grup "{groupName}" oleh admin.',
    'group_detail_success_kicked': '{user} berhasil dikeluarkan dari grup',
    'group_detail_err_kicked': 'Gagal mengeluarkan anggota: Koneksi bermasalah atau coba lagi ({error})',
    'group_detail_err_load_members': 'Gagal memuat anggota: {error}',
    'group_detail_deadline_dialog_title': 'Pilih Tanggal Tenggat Baru',
    'group_detail_notif_deadline_title': '⏰ Tenggat Grup Diperbarui',
    'group_detail_notif_deadline_body': '{admin} mengubah tenggat waktu grup "{groupName}" menjadi {date}.',
    'group_detail_success_deadline': '✅ Tenggat waktu berhasil diperbarui!',
    'group_detail_err_deadline': 'Gagal memperbarui tenggat waktu: {error}',
    'group_detail_settings_title': 'Pengaturan Grup',
    'group_detail_settings_share': 'Bagikan Kode Undangan',
    'group_detail_settings_type': 'Tipe Grup',
    'group_detail_settings_type_rutin_desc': '🔁 RUTIN: Siklus berulang tanpa diarsip, mendukung Rolling Juz',
    'group_detail_settings_type_insidental_desc': '⚡ INSIDENTAL: Satu kali putaran selesai lalu diarsip',
    'group_detail_settings_type_success': 'Tipe grup diubah menjadi {val}!',
    'group_detail_settings_type_failed': 'Gagal mengubah tipe grup: {error}',
    'group_detail_settings_limit': 'Batasi Pengambilan Juz',
    'group_detail_settings_limit_active': '🔒 Aktif: Maksimal {count} Juz per anggota',
    'group_detail_settings_limit_inactive': '🔓 Bebas: Anggota bebas mengambil tanpa batas',
    'group_detail_settings_limit_rls': 'Izin update ditolak (RLS).',
    'group_detail_settings_limit_success_active': '🔒 Batasan pengambilan Juz diaktifkan!',
    'group_detail_settings_limit_success_inactive': '🔓 Batasan pengambilan Juz dinonaktifkan!',
    'group_detail_settings_limit_failed': 'Gagal mengubah batasan: {error}',
    'group_detail_settings_manage': 'Kelola Anggota',
    'group_detail_settings_manage_desc': 'Setujui permintaan masuk & tambah anggota baru',
    'group_detail_settings_assign': 'Pembagian Juz (Admin)',
    'group_detail_settings_deadline': 'Ubah Tenggat Waktu (Deadline)',
    'group_detail_settings_deadline_desc': 'Perpanjang atau majukan target waktu siklus',
    'group_detail_settings_history': 'Riwayat Putaran',
    'group_detail_settings_history_desc': 'Lihat daftar putaran khataman yang telah selesai',
    'group_detail_settings_leave': 'Keluar dari Grup',
    'group_detail_settings_leave_desc': 'Keluar dan serahkan kepemilikan admin ke anggota lain',
    'group_detail_settings_delete': 'Hapus Grup',
    'group_detail_settings_delete_desc': 'Hapus grup ini secara permanen dari server',
    'group_detail_settings_view_members': 'Daftar Anggota',
    'group_detail_settings_view_members_desc': 'Lihat anggota grup saat ini',
    'group_detail_settings_leave_member_desc': 'Keluar dan lepaskan semua juz yang Anda klaim',
    'group_detail_members_empty': 'Belum ada anggota lain.',
    'group_detail_members_err': 'Gagal memuat daftar anggota: {error}',
    'group_detail_history_title': 'Riwayat Khataman',
    'group_detail_history_subtitle': 'Daftar putaran khataman grup yang selesai',
    'group_detail_history_err': 'Gagal memuat riwayat: {error}',
    'group_detail_history_empty_title': 'Belum ada Riwayat Khataman',
    'group_detail_history_empty_body': 'Selesaikan target 30 Juz pada putaran aktif untuk mencatatkan riwayat khataman pertama grup Anda!',
    'group_detail_history_great_achievement': 'Pencapaian Luar Biasa!',
    'group_detail_history_completed_count': 'Total {count} Kali Khatam Al-Quran',
    'group_detail_history_blessing_text': 'Semoga berkah dan istiqomah untuk setiap baris ayat yang dibaca bersama.',
    'group_detail_cycle_number': 'Putaran Ke-{number}',
    'group_detail_cycle_detail_err': 'Gagal memuat detail pembaca atau data slot tidak ditemukan.',
    'group_detail_cycle_detail_title': 'Daftar Pembaca per Juz:',
    'group_detail_cycle_detail_free': 'Umum',
    'group_detail_cycle_detail_juz_user': 'Juz {juz}: @{user}',
    'group_detail_leave_dialog_title': 'Keluar Grup?',
    'group_detail_leave_dialog_body': 'Apakah Anda yakin ingin keluar dari grup khataman ini? Semua juz yang telah Anda klaim akan dilepaskan kembali.',
    'group_detail_leave_dialog_confirm': 'Keluar',
    'group_detail_leave_success': 'Anda telah keluar dari grup.',
    'group_detail_leave_failed': 'Gagal keluar grup: {error}',
    'group_detail_delete_dialog_title': 'Hapus Grup?',
    'group_detail_delete_dialog_body': 'Grup ini dan semua progres di dalamnya akan dihapus secara permanen. Tindakan ini tidak dapat dibatalkan.',
    'group_detail_delete_confirm': 'Ya, Hapus',
    'group_detail_notif_delete_title': 'Grup Khataman Dihapus 🗑️',
    'group_detail_notif_delete_body': 'Grup "{groupName}" telah dihapus oleh admin.',
    'group_detail_delete_failed': 'Grup gagal dihapus. Anda mungkin tidak memiliki izin (RLS) di database.',
    'group_detail_delete_success': 'Grup berhasil dihapus',
    'group_detail_delete_err_dialog_title': 'Gagal Menghapus Grup',
    'group_detail_completed_count_badge': '🏆 {count} Kali Khataman Selesai!',
    'group_detail_view_history_link': 'Lihat Riwayat Lengkap ➔',
    'group_detail_join_code_label': 'Kode Bergabung',
    'group_detail_copied_link': 'Link undangan grup berhasil disalin! 🔗',
    'group_detail_copy_instruction': 'Tekan lama untuk menyalin',
    'group_detail_share_title': 'Bagikan Kode Undangan',
    'group_detail_share_instruction': 'Tekan lama kode untuk menyalin, atau ketuk ikon bagikan untuk menyebarkan.',
    'group_detail_members_count_label': 'Anggota Bergabung ({count})',
    'group_detail_settings_limit_active_badge': 'Batasan Pengambilan Juz: AKTIF (Maks {count} Juz)',
    'group_detail_settings_limit_inactive_badge': 'Batasan Pengambilan Juz: NONAKTIF (Bebas)',
    'group_detail_roll_title_random': 'Rolling Juz (Acak Cerdas)',
    'group_detail_roll_title_equal': 'Bagi Rata Otomatis',
    'group_detail_roll_title_manual': 'Bagi Manual (Kuas Admin)',
    'group_detail_roll_title_claim': 'Klaim Mandiri (Open Slot)',
    'group_detail_confirm_cycle_complete_title': 'Konfirmasi Selesai Putaran',
    'group_detail_confirm_archive_title': 'Konfirmasi Khataman Grup',
    'group_detail_confirm_cycle_complete_desc': 'Jika sudah, putaran siklus ini akan diselesaikan dan dicatat ke dalam riwayat grup. Anda dapat langsung memulai putaran berikutnya.',
    'group_detail_confirm_archive_desc': 'Jika sudah, grup ini akan diarsipkan dan progres khataman akan dicatat ke dalam riwayat semua anggota. Anggota lain akan menerima notifikasi.',
    'group_detail_confirm_cycle_complete_instruction': 'Tindakan ini akan menyelesaikan putaran siklus ini dan mencatatnya ke riwayat grup. Anda dapat langsung memulai putaran berikutnya. Lanjutkan?',
    'group_detail_confirm_archive_instruction': 'Tindakan ini akan menyelesaikan progres khataman, mengarsipkan grup ini secara permanen, dan mencatatnya ke riwayat seluruh anggota. Lanjutkan?',
    'group_detail_btn_doa': 'Belum, Baca Doa',
    'group_detail_btn_yes': 'Ya, Sudah',
    'group_detail_notif_cycle_complete_title': '🎉 Putaran Khataman Selesai!',
    'group_detail_notif_archive_title': '📁 Khataman Diarsipkan',
    'group_detail_notif_cycle_complete_body': '"{groupName}" telah menyelesaikan putaran siklus oleh {user}. Alhamdulillah!',
    'group_detail_notif_archive_body': '"{groupName}" telah diarsipkan oleh {user} setelah menyelesaikan Doa Khatam Al-Quran. Alhamdulillah!',
    'group_detail_success_cycle_complete': '🎉 Putaran khataman berhasil diselesaikan!',
    'group_detail_success_archive': '📁 Grup telah diarsipkan. Alhamdulillah!',
    'group_detail_err_cycle_complete': 'Gagal menyelesaikan khataman: {error}',
    'group_detail_cycle_title': 'Putaran {number}',
    'group_detail_unlimited_juz': 'Bebas mengambil Juz',
    'group_detail_celebration_alhamdulillah_desc': 'Alhamdulillah! Grup "{groupName}" telah menyelesaikan siklus khataman 30 Juz Al-Quran.',
    'group_detail_btn_new_cycle': 'Putaran Baru',
    'group_detail_archived_banner': 'Grup ini telah diarsipkan. Progres khataman sudah dicatat ke riwayat.',
    'group_detail_transfer_single_member': 'Anda adalah Admin grup "{groupName}". Pilih anggota aktif untuk menggantikan kepemimpinan Anda sebelum keluar:',
    'group_detail_btn_confirm_continue': 'Konfirmasi & Lanjut',
    'group_detail_kick_only_member_title': 'Keluar & Hapus Grup?',
    'group_detail_kick_only_member_body': 'Anda adalah satu-satunya anggota di grup ini. Jika Anda keluar, grup ini akan dihapus secara permanen dari server. Lanjutkan?',
    'group_detail_kick_only_member_confirm': 'Keluar & Hapus',
    'group_detail_success_transfer_leave': 'Berhasil menyerahkan admin dan keluar dari grup.',
    'group_detail_err_transfer_leave': 'Gagal keluar dari grup: {error}',

    // Juz Assignment Screen
    'juz_assign_title': 'Pembagian Juz',
    'juz_assign_notif_release_req_title': 'Persetujuan Lepas Juz',
    'juz_assign_notif_release_req_body': 'Anggota "{user}" mengajukan untuk melepas Juz {juz}.',
    'juz_assign_success_release': 'Juz {juz} berhasil dilepas.',
    'juz_assign_err_approve': 'Gagal menyetujui: {error}',
    'juz_assign_err_reject': 'Gagal menolak: {error}',
    'juz_assign_success_reject': 'Pengajuan lepas Juz {juz} ditolak.',
    'juz_assign_err_limit_exceeded': 'Gagal! Anggota ini sudah mencapai batas maksimal pembagian rata ({limit} Juz).',
    'juz_assign_transfer_title': 'Pindahkan Pembagian Juz?',
    'juz_assign_transfer_body': 'Juz ini sudah ditugaskan tetapi BELUM mulai dibaca. Apakah Anda yakin ingin memindahkannya?',
    'juz_assign_transfer_no': 'Tidak',
    'juz_assign_transfer_yes': 'Ya, Pindahkan',
    'juz_assign_progress_exists_title': 'Juz Sudah Dibaca!',
    'juz_assign_progress_exists_body': 'Juz {juz} ini sudah memiliki progres membaca. Apakah Anda yakin ingin memaksa mengubah pembagian atau menghapus progresnya? Tindakan ini akan mereset progres pembacaan juz tersebut.',
    'juz_assign_progress_exists_yes': 'Ya, Paksa Ubah',
    'juz_assign_confirm_save_title': 'Simpan Perubahan?',
    'juz_assign_confirm_save_body': 'Anda memiliki draf pembagian Juz yang belum disimpan. Apakah Anda ingin menyimpan perubahan tersebut?',
    'juz_assign_confirm_save_discard': 'Buang',
    'juz_assign_confirm_save_success': '✅ Pembagian Juz berhasil disimpan!',
    'juz_assign_brush_eraser': 'Penghapus',
    'juz_assign_brush_info_delete': 'Kuas Hapus aktif! Ketuk kotak Juz untuk mengosongkan pembagian.',
    'juz_assign_brush_info_draw': 'Kuas aktif! Ketuk kotak Juz untuk membagi langsung.',
    'juz_assign_empty_cycle': 'Tidak ada siklus aktif',
    'juz_assign_empty_cycle_desc': 'Mulai putaran siklus baru terlebih dahulu.',
    'juz_assign_btn_reset': 'Reset Perubahan',
    'juz_assign_success_reset': 'Draf pembagian yang belum dibaca berhasil dibersihkan',
    'juz_assign_btn_clear_all': 'Bersihkan Semua',
    'juz_assign_brush_members': '🎨 Kuas Anggota',

  },
  'en': {
    'title_settings': 'Settings',
    'section_appearance': 'Appearance',
    'tile_theme': 'App Theme',
    'theme_dark': 'Dark',
    'theme_light': 'Light',
    'tile_font_size': 'Text Size',
    'font_size_small': 'Small',
    'font_size_normal': 'Normal',
    'font_size_large': 'Large',
    'section_notifications': 'Notifications',
    'tile_reminder': 'Khataman Reminder',
    'status_active': 'Active',
    'status_inactive': 'Inactive',
    'tile_reminder_time': 'Reminder Time',
    'tile_group_notif': 'Group Update Notifications',
    'subtitle_group_notif': 'When members claim or complete a Juz',
    'section_prayer_azan': 'Prayer & Adhan',
    'tile_azan_notif': 'Adhan Notifications',
    'tile_azan_sound': 'Adhan Sound',
    'tile_calc_method': 'Calculation Method',
    'tile_madhab': 'Madhab',
    'section_reading_target': 'Reading Target',
    'tile_daily_target': 'Daily Target',
    'text_daily_target_prefix': 'Read ',
    'text_daily_target_suffix': ' Juz per day',
    'section_about': 'About',
    'tile_about_app': 'About Application',
    'tile_privacy_policy': 'Privacy Policy',
    'subtitle_privacy_policy': 'How we protect your data',
    'tile_changelog': 'Changelog',
    'subtitle_changelog': 'App update history & versions',
    'section_account': 'Account',
    'tile_delete_account': 'Delete Account',
    'subtitle_delete_account': 'Permanently delete your account and all data',
    'tile_language': 'Language / Bahasa',
    'dialog_choose_language': 'Select Language / Pilih Bahasa',
    'btn_cancel': 'Cancel',
    'btn_save': 'Save',
    'btn_close': 'Close',

    // Sounds
    'sound_default': 'System Default Sound',
    'sound_silent': 'Silent (Vibrate Only)',
    'sound_makkah': 'Makkah Adhan',
    'sound_madinah': 'Madinah Adhan',

    // Calculation Methods
    'method_kemenag': 'Indonesian Ministry of Religious Affairs (Kemenag)',
    'method_singapore': 'MUIS Singapore',
    'method_muslim_world_league': 'Muslim World League (MWL)',
    'method_egyptian': 'Egyptian General Authority of Survey',
    'method_karachi': 'University of Islamic Sciences, Karachi',
    'method_umm_al_qura': 'Umm Al-Qura, Makkah',
    'method_dubai': 'Dubai',
    'method_kuwait': 'Kuwait',
    'method_turkey': 'Turkey Diyanet',
    'method_tehran': 'Institute of Geophysics University of Tehran',

    // Madhabs
    'madhab_syafii': 'Shafi\'i (Standard)',
    'madhab_hanafi': 'Hanafi',
    'madhab_desc_syafii': 'Used in Indonesia, Malaysia, etc.',
    'madhab_desc_hanafi': 'Used in Turkey, Pakistan, etc.',

    // About Dialog
    'about_title': 'About Khataman Quran',
    'about_version': 'Version',
    'about_desc': 'Application to track Khataman Al-Quran progress individually or together in groups.',
    'about_tech_stack': 'Technology Stack:',

    // Privacy Policy Dialog
    'policy_intro': 'We highly value your privacy and data protection. The Khataman Quran application is designed with full transparency principles:',
    'policy_1_title': '1. Data Collection',
    'policy_1_body': 'The application synchronizes your reading progress data (claimed/completed Juz, khataman history) to a secure Supabase Cloud database for smooth cross-device access.',
    'policy_2_title': '2. User Authentication',
    'policy_2_body': 'We use your email (via Google Sign-In or Email Auth) solely for account security, group ownership, and history synchronization.',
    'policy_3_title': '3. Full Confidentiality',
    'policy_3_body': 'Your personal data and progress will never be sold, shared, or misused to any third party.',
    'policy_4_title': '4. Account Deletion Rights',
    'policy_4_body': 'You have the absolute right to delete all your data at any time. Through the "Delete Account" button, all profiles, self-owned group data, history, and data relations in our server database will be deleted instantly and permanently without trace.',
    'policy_dialog_close': 'I Understand',

    // Delete Account Dialog
    'delete_confirm_title': 'Delete Account?',
    'delete_confirm_body': 'All your data (personal reading progress, reading history, and group membership) will be permanently DELETED.\n\nThis action cannot be undone.',
    'delete_confirm_type_sentence': 'To confirm, type the sentence below:',
    'delete_verify_text': 'yes, i want to DELETE this account',
    'delete_verify_hint': 'Type verification sentence here...',
    'delete_btn_yes': 'Yes, Delete',
    'msg_delete_cancelled': 'Account deletion cancelled.',
    'msg_delete_failed': 'Failed to delete account',
    
    // New Admin Dialog
    'dialog_title_new_admin': 'Choose New Admin',
    'dialog_body_new_admin': 'You are the Admin of group "{groupName}". Select an active member to replace your leadership before your account is deleted:',
    'btn_confirm_continue': 'Confirm & Continue',

    // Changelog
    'changelog_title': 'Changelog',
    'changelog_v1_13_0_header': 'v1.13.0 (June 2026)',
    'changelog_v1_13_0_1': '✨ Shimmer Loading: Home screen loading transition using unified and elegant Shimmer effects.',
    'changelog_v1_13_0_2': '🕋 Precision Compass: Dynamic Kaaba icon revolving around the compass following the qibla needle, equipped with vibration/haptic feedback.',
    'changelog_v1_13_0_3': '⚡ In-Memory Caching & Offline: Instant 0ms navigation on home, group, personal, and prayer schedule using local cache, with offline warning banners.',
    'changelog_v1_13_0_4': '📍 Custom Prayer Location: Manual search for cities/coordinates and instant prayer time updates.',
    'changelog_v1_13_0_5': '↩️ SnackBar Undo: "Undo" button to restore database records when deleting notifications individually.',
    
    'changelog_v1_1_0_header': 'v1.1.0 (May 2026)',
    'changelog_v1_1_0_1': '✨ Premium Aesthetics: Alignment of height (48px), roundness (circular 12), and smart colors for "I Have Read", "Save Progress", and "Release" buttons (Light & Dark Mode).',
    'changelog_v1_1_0_2': '👑 Interactive Self-Delete: Support for transferring group leadership (admin) via manual member selection dialog before account deletion.',
    'changelog_v1_1_0_3': '🔒 Smart Preservation (Snapshot): Fully completed Juz (100%) are retained as group history snapshot, while incomplete Juz are automatically released for other members.',
    'changelog_v1_1_0_4': '🔔 Cross-Platform Reminder: Web browser notification support (HTML5 Notification API) in Chrome and auto-permission queries for Android 13+ & iOS.',
    'changelog_v1_1_0_5': '📜 Changelog & Privacy: Added transparent Privacy Policy dialog and interactive Changelog menu on settings page.',
    
    'changelog_v1_0_0_header': 'v1.0.0 (Early 2026)',
    'changelog_v1_0_0_1': '📖 Personal Khatam: Track personal Al-Quran reading Juz 1 - 30 with interactive progress visuals.',
    'changelog_v1_0_0_2': '👥 Group Khatam: Join or create groups with peers to cooperatively complete 30 Juz.',
    'changelog_v1_0_0_3': '☁️ Supabase Cloud Sync: Instant two-way sync of all history and reading progress in real-time.',
    'changelog_v1_0_0_4': '🌗 Dynamic Theme: Eye-friendly Light & Dark Mode support for reading comfort.',

    // Prayer Names
    'prayer_imsak': 'Imsak',
    'prayer_subuh': 'Fajr',
    'prayer_syuruk': 'Sunrise',
    'prayer_dhuha': 'Duha',
    'prayer_dzuhur': 'Dhuhr',
    'prayer_ashar': 'Asr',
    'prayer_maghrib': 'Maghrib',
    'prayer_isya': 'Isha',
    'tile_azan_format': '{prayer} Adhan',
    
    // Add missing targets
    'target_daily_target_juz': 'Read {target} per day',
    'target_1_10': '1/10 Juz (2 Pages) per day',
    'target_1_8': '1/8 Juz (2.5 Pages) per day',
    'target_1_4': '1/4 Juz (5 Pages) per day',
    'target_1_2': '1/2 Juz (10 Pages) per day',
    'target_3_4': '3/4 Juz (15 Pages) per day',
    'target_1': '1 Juz (20 Pages) per day',
    'target_2': '2 Juz (40 Pages) per day',
    'target_3': '3 Juz (60 Pages) per day',
    'target_4': '4 Juz (80 Pages) per day',
    'target_5': '5 Juz (100 Pages) per day',

    // Other settings
    'footer_made_with': 'Made with ❤️ for the Ummah',

    // Home Dashboard
    'home_fallback_name': 'Servant of Allah',
    'home_greeting': 'Assalamu\'alaikum,',
    'home_tooltip_notification': 'Notifications',
    'home_tooltip_settings': 'Settings',
    'home_active_khataman': 'Your Active Khataman',
    'home_btn_quick_update': 'Quick Update Progress',
    'home_empty_slot_title': 'Slot Available',
    'home_empty_slot_desc': 'Start a new khataman program',
    'home_show_less': 'Show Less',
    'home_show_more': 'Show More',
    'home_type_group': 'Group',
    'home_type_mandiri': 'Personal',
    'home_start_now': 'Start Now',
    'home_feat_mushaf_title': 'Mushaf Al-Quran',
    'home_feat_mushaf_subtitle': 'Read Al-Quran offline with translation',
    'home_feat_mandiri_title': 'Personal Khataman',
    'home_feat_mandiri_subtitle': 'Track your personal Al-Quran reading progress',
    'home_feat_group_title': 'Group Khataman',
    'home_feat_group_subtitle': 'Complete Al-Quran with group members',
    'home_feat_prayer_title': 'Prayer Times',
    'home_feat_prayer_subtitle': 'Prayer times, countdown, & adhan notifications',
    'home_feat_qibla_title': 'Qibla Direction',
    'home_feat_qibla_subtitle': 'Digital compass pointing to the Kaaba',
    'home_stat_total_juz': 'Total Juz',
    'home_stat_surah': 'Surah',
    'home_stat_ayat': 'Ayah',
    'home_history_header': '🏆  MY HISTORY & STATISTICS',
    'home_history_title_completed': 'Alhamdulillah, Completed {count} Times',
    'home_history_title_empty': 'Monitor Your Progress & Statistics',
    'home_history_subtitle': 'View reading history for this week, month, & year ➔',
    'home_join_group_not_found': 'Group with code "{code}" not found.',
    'home_join_group_pending': 'Your request to join "{groupName}" is still PENDING Admin approval.',
    'home_join_group_rejected': 'Your membership in "{groupName}" has been rejected/suspended.',
    'home_join_group_failed_link': 'Failed to process link: {error}',
    'home_join_dialog_title': 'Join Group',
    'home_join_dialog_body': 'Do you want to request to join group "{groupName}" (Code: {code})?',
    'home_join_dialog_cancel': 'Cancel',
    'home_join_dialog_confirm': 'Join',
    'home_join_sent_pending': 'Join request sent! Waiting for Admin approval.',
    'home_join_success': 'Successfully joined "{groupName}"!',
    'home_join_failed': 'Failed to join: {error}',
    'home_notif_new': 'New Notification',
    'home_notif_silent_title': 'Group Notification (Silent)',
    'home_notif_default_title': 'Group Notification (Sound)',
    'home_notif_silent_desc': 'Silent group notification to avoid prayer time overlap',
    'home_notif_default_desc': 'Group notification with default sound',

    // Mandiri Screen
    'mandiri_max_ayat_error': 'Ayah number exceeds maximum limit (Max: {total})',
    'mandiri_log_juz_completed': 'Alhamdulillah, completed Juz {juz}!',
    'mandiri_save_failed': 'Failed to save: {error}',
    'mandiri_reset_dialog_title': 'Start New Khatam?',
    'mandiri_reset_dialog_body': 'Current reading progress will be restarted. Previous khatam history will remain saved.',
    'mandiri_reset_dialog_cancel': 'Cancel',
    'mandiri_reset_dialog_confirm': 'Restart',
    'mandiri_reset_success': 'Progress successfully reset. Bismillah, start again! 🌙',
    'mandiri_reset_failed': 'Failed to reset: {error}',
    'mandiri_confirm_khatam_title': 'Confirm Khataman',
    'mandiri_confirm_khatam_body': 'Have you finished reading the Doa Khatam Al-Quran?\n\nIf so, your khatam progress will be recorded in history and reset back to Juz 1.',
    'mandiri_confirm_khatam_instruction': 'This action will record your Personal Khatam to history and reset all progress back to Juz 1 to start a new cycle. Continue?',
    'mandiri_btn_read_doa': 'Not Yet, Read Doa',
    'mandiri_btn_yes_done': 'Yes, Finished',
    'mandiri_log_khatam_completed': '🏆 Completed Personal Khatam of 30 Juz! Alhamdulillah!',
    'mandiri_khatam_logged': '🏆 Khatam successfully recorded! Bismillah, start again!',
    'mandiri_khatam_failed': 'Failed to record khatam: {error}',
    'mandiri_title': 'Personal Khataman',
    'mandiri_tooltip_reset': 'Reset All Progress',
    'mandiri_btn_reset_khatam': 'Start New Khataman',
    'mandiri_progress_title': 'Khatam Progress',
    'mandiri_juz_completed_count': '{completed} / 30 Juz Completed',
    'mandiri_progress_short': 'Personal Progress: {completed}/30 Juz',
    'mandiri_offline_banner': 'Connection Lost. Showing last offline data.',

    // Doa Khatam Component
    'doa_title': 'Doa Khatam Al-Quran',
    'doa_transliteration_header': 'Transliteration:',
    'doa_translation_header': 'Translation:',
    'doa_translation_text': '“O Allah, have mercy on me with the Quran. Make it for me a guide, a light, a guidance, and a mercy. O Allah, remind me of what I have forgotten from it, teach me what I do not know of it, and grant me its recitation during the hours of night and the ends of day. And make it a proof for me, O Lord of the worlds.”',
    'doa_confirm_complete_title': 'Complete Khataman?',
    'doa_confirm_complete_body': 'This action will record the khatam to history and complete the current cycle progress. Continue?',
    'doa_btn_yes_complete': 'Yes, Complete',
    'doa_btn_read_already': 'I Have Read the Doa',
    'congrats_title': 'Maa Syaa Allah, Barakallah! 🎉',
    'congrats_desc': 'Congratulations! You have completed the khatam of 30 Juz Al-Quran.',
    'congrats_btn_reset': 'Reset Progress',
    'congrats_btn_doa': 'Doa Khatam',

    // Qibla Screen
    'qibla_loading_location': 'Loading location...',
    'qibla_fallback_location': 'Your Location',
    'qibla_title': 'Qibla Direction',
    'qibla_distance_suffix': 'km to Kaaba',
    'qibla_active_compass': 'Compass Active',
    'qibla_aligned': 'You Are Facing Qibla! ✅',
    'qibla_turn_device': 'Turn your device towards Kaaba',
    'qibla_offset_text': '{offset}° offset from your position',
    'qibla_calibration_tip': 'Tip: Wave your phone in a figure-8 motion to calibrate the compass sensor.',
    'qibla_sensor_unavailable': 'Sensor Unavailable',
    'qibla_sensor_fallback': 'Your device does not have a magnetometer sensor. Showing static Qibla direction.',
    'qibla_location_unavailable': 'Location unavailable.\nPlease open the Prayer Times screen first to detect location.',
    'qibla_static_heading': 'Qibla Direction: {bearing}° from North',
    'qibla_static_distance': 'Distance to Kaaba: {distance} km',
    'qibla_static_from': 'From: {location}',

    // Prayer Time Screen
    'prayer_title': 'Prayer Times',
    'prayer_tooltip_settings': 'Calculation Settings',
    'prayer_btn_refresh': 'Refresh',
    'prayer_next_prayer': 'Next Prayer Time',
    'prayer_all_done': 'All Prayers Completed Today',
    'prayer_at_time': 'at {time}',
    'prayer_alhamdulillah': 'Alhamdulillah 🤲',
    'prayer_fard_badge': 'FARD',
    'prayer_method_madhab_info': 'Method: {method} • Madhab: {madhab}',
    'prayer_err_general': 'An error occurred',
    'prayer_btn_retry': 'Retry',
    'prayer_err_enter_city': 'Please enter a city name first',
    'prayer_err_no_internet': 'No internet connection',
    'prayer_err_city_not_found': 'City "{query}" not found',
    'prayer_success_city_changed': 'Location changed to: {resolvedName}',
    'prayer_err_failed_search': 'Failed to search location. Make sure spelling is correct.',
    'prayer_settings_title': 'Prayer & Adhan Settings',
    'prayer_settings_loc_section': 'Location Settings',
    'prayer_settings_use_gps': 'Use Automatic GPS',
    'prayer_settings_use_gps_sub': 'Search location based on real-time device position',
    'prayer_settings_city_hint': 'Enter city name (e.g., London)',
    'prayer_settings_active_loc': 'Active location: {city}',
    'prayer_settings_calc_title': 'Calculation Method',
    'prayer_settings_madhab_title': 'Madhab (Asr Timing Rule)',
    'prayer_settings_azan_alarm': 'Adhan Alarm Notification',
    'prayer_settings_azan_reminder_time': 'Prayers to Notify:',
    'prayer_settings_azan_sound_selection': 'Adhan Sound Selection',
    'prayer_settings_btn_save': 'Save & Apply',
    'prayer_offline_banner': 'Connection Lost. Showing last offline data.',
    'prayer_unknown_location': 'Unknown Location',
    'prayer_saved_location': 'Saved Location',
    'prayer_default_location': 'Jakarta, Indonesia (Default)',
    'day_monday': 'Monday',
    'day_tuesday': 'Tuesday',
    'day_wednesday': 'Wednesday',
    'day_thursday': 'Thursday',
    'day_friday': 'Friday',
    'day_saturday': 'Saturday',
    'day_sunday': 'Sunday',
    'month_january': 'January',
    'month_february': 'February',
    'month_march': 'March',
    'month_april': 'April',
    'month_may': 'May',
    'month_june': 'June',
    'month_july': 'July',
    'month_august': 'August',
    'month_september': 'September',
    'month_october': 'October',
    'month_november': 'November',
    'month_december': 'December',

    // Profile Screen
    'profile_err_empty_username': 'Username cannot be empty',
    'profile_err_min_char': 'Username must be at least 3 characters',
    'profile_err_invalid_char': 'Username can only contain letters, numbers, dot (.), and underscore (_)',
    'profile_success_username_changed': 'Username successfully changed!',
    'profile_err_username_taken': 'Username is already taken by someone else, try another',
    'profile_confirm_logout_title': 'Log Out?',
    'profile_confirm_logout_body': 'You will be logged out of this account.',
    'profile_confirm_logout_yes': 'Yes, Log Out',
    'profile_title': 'My Profile',
    'profile_fallback_username': 'User',
    'profile_username_rules': 'Username Rules:\n• Minimum 3 characters\n• Only letters (a-z), numbers (0-9), dot (.), & underscore (_)',
    'profile_btn_edit': 'Edit',
    'profile_hint_new_username': 'Enter new username',
    'profile_rule_min_char': 'Minimum 3 characters',
    'profile_rule_valid_char': 'Only letters, numbers, dot (.), and underscore (_)',
    'profile_tile_email': 'Email',
    'profile_tile_login_with': 'Logged in with',
    'profile_tile_joined_since': 'Joined since',
    'profile_btn_logout': 'Log Out of Account',
    'month_jan_short': 'Jan',
    'month_feb_short': 'Feb',
    'month_mar_short': 'Mar',
    'month_apr_short': 'Apr',
    'month_may_short': 'May',
    'month_jun_short': 'Jun',
    'month_jul_short': 'Jul',
    'month_aug_short': 'Aug',
    'month_sep_short': 'Sep',
    'month_oct_short': 'Oct',
    'month_nov_short': 'Nov',
    'month_dec_short': 'Dec',

    // History Screen
    'history_cycle_title_mandiri': 'Personal Khataman',
    'history_cycle_desc_mandiri': '🏆 Completed Personal Khatam of 30 Juz!',
    'history_cycle_title_group': 'Group Khataman "{groupName}"',
    'history_cycle_desc_group': '🏆 Completed Group Khatam with "{groupName}"! Contributed {count} Juz.',
    'history_cycle_group_fallback': 'Group',
    'history_info_tooltip': 'Total number of completed Quran Khatams, combining Personal progress and Group contributions.',
    'history_confirm_clear_title': 'Clear All History?',
    'history_confirm_clear_body': 'All your reading activity records and personal khatam statistics will be permanently deleted.\n\nThis action cannot be undone.',
    'history_confirm_clear_yes': 'Yes, Clear All',
    'history_clear_success': 'Your entire personal history has been cleared.',
    'history_time_just_now': 'Just now',
    'history_time_minutes_ago': '{minutes} minutes ago',
    'history_time_hours_ago': '{hours} hours ago',
    'history_time_yesterday': 'Yesterday, {time}',
    'history_title': 'My History & Stats',
    'history_stat_title_total': 'TOTAL KHATAM AL-QURAN',
    'history_stat_count_suffix': 'Times',
    'history_stat_khatam_label': '30 Juz Khatam',
    'history_section_my_stats': 'My Reading Statistics',
    'history_stat_week': 'This Week',
    'history_stat_month': 'This Month',
    'history_stat_year': 'This Year',
    'history_stat_juz_completed': 'Juz Completed',
    'history_section_log_title': 'Activity History Log',
    'history_section_log_count': '{count} Khatams',
    'history_empty_title': 'Start Reading Al-Quran',
    'history_empty_body': 'Save your reading progress in Personal Khatam or Group Khatam to see your reading history here.',
    'history_detail_read_juz': 'Details of Juz Read:',
    'history_detail_no_juz': 'No juz details recorded.',

    // Notifications Screen
    'notif_request_processed': 'Request has been processed',
    'notif_join_approved_msg': 'Join request successfully approved',
    'notif_join_approve_failed': 'Failed to approve request: {error}',
    'notif_reject_confirm_title': 'Reject Request?',
    'notif_reject_confirm_body': 'Are you sure you want to reject this join request?',
    'notif_reject_btn_confirm': 'Reject',
    'notif_join_rejected_msg': 'Join request successfully rejected',
    'notif_join_reject_failed': 'Failed to reject request: {error}',
    'notif_release_approved_msg': 'Juz release request successfully approved',
    'notif_release_approve_failed': 'Failed to approve release: {error}',
    'notif_release_reject_title': 'Reject Request?',
    'notif_release_reject_body': 'Are you sure you want to reject this Juz {juz} release request?',
    'notif_release_rejected_msg': 'Juz release request successfully rejected',
    'notif_release_reject_failed': 'Failed to reject release: {error}',
    'notif_mark_all_read_msg': 'All notifications marked as read',
    'notif_delete_success': 'Notification successfully deleted 🗑️',
    'notif_undo_label': 'UNDO',
    'notif_undo_failed': 'Failed to undo deletion: {error}',
    'notif_delete_failed': 'Failed to delete notification: {error}',
    'notif_clear_all_title': 'Delete All Notifications?',
    'notif_clear_all_body': 'Are you sure you want to delete all your notification history? This action cannot be undone.',
    'notif_clear_all_confirm': 'Delete All',
    'notif_clear_all_success': 'All notifications successfully cleared',
    'notif_clear_all_failed': 'Failed to delete all notifications: {error}',
    'notif_title': 'Notifications',
    'notif_btn_mark_read': 'Mark all as read',
    'notif_btn_clear_all': 'Clear all notifications',
    'notif_badge_processed': 'Request has been processed',
    'notif_badge_approved': 'Approved',
    'notif_badge_rejected': 'Rejected',
    'notif_badge_cancelled_label': 'Request cancelled',
    'notif_badge_rejected_label': 'Request rejected',
    'notif_badge_approved_label': 'Request approved',
    'notif_badge_release_approved_label': 'Juz release request approved',
    'notif_badge_release_rejected_label': 'Juz release request rejected',
    'notif_btn_approve_action': 'Approve',
    'notif_btn_reject_action': 'Reject',
    'notif_empty_title': 'No Notifications Yet',
    'notif_empty_body': 'Your group activities will appear here.',
    'notif_join_cancelled_title': 'Request Cancelled',
    'notif_time_just_now': 'Just now',
    'notif_time_minutes_ago': '{minutes} minutes ago',
    'notif_time_hours_ago': '{hours} hours ago',
    'notif_time_days_ago': '{days} days ago',

    // Mushaf Screen
    'mushaf_title': 'Mushaf Al-Quran',
    'mushaf_tab_surah': 'Surah',
    'mushaf_tab_juz': 'Juz',
    'mushaf_last_read_header': 'Last Read',
    'mushaf_last_read_surah_ayat': 'Surah {surah} (Ayah {ayat})',
    'mushaf_last_read_juz': 'Juz {juz}',
    'mushaf_last_read_continue': 'Continue',
    'mushaf_search_hint': 'Search surah (e.g. Yasin, Al-Mulk...)',
    'mushaf_makkiyah': 'Makkiyah',
    'mushaf_madaniyah': 'Madaniyah',
    'mushaf_verses_count': '{count} Verses',
    'mushaf_juz_detail_single': 'Surah {surah} (Ayah {start}-{end})',
    'mushaf_juz_detail_multi': 'Surah {start} to {end}',
    'mushaf_empty_search': 'Surah not found',

    // Mushaf Reader Screen
    'mushaf_reader_bookmark_saved': 'Bookmark saved: Surah {surah} ayah {ayat}',
    'mushaf_reader_err_reverse': 'You have already read this verse.',
    'mushaf_reader_log_juz_completed_mushaf': 'Alhamdulillah, completed Juz {juz} via Mushaf!',
    'mushaf_reader_notif_completed_title': 'Juz Completed',
    'mushaf_reader_notif_completed_body': '{user} has completed Juz {juz} in group "{group}" via Mushaf',
    'mushaf_reader_success_completed': '✅ Juz {juz} completed! Progress successfully synchronized!',
    'mushaf_reader_success_saved': 'Progress successfully saved!',
    'mushaf_reader_err_save': 'Failed to save progress: {error}',
    'mushaf_reader_settings_title': 'Display Settings',
    'mushaf_reader_arabic_text_size': 'Arabic Text Size',
    'mushaf_reader_translation_text_size': 'Translation Size',
    'mushaf_reader_show_translation': 'Show Translation',
    'mushaf_reader_selected_verse_title': 'Selected Ayah',
    'mushaf_reader_bookmark_label': 'Bookmark',
    'mushaf_reader_juz_progress_text': 'Juz {juz} • Progress: {current} / {total} Ayah ({percent}%)',
    'mushaf_reader_mark_juz_done': 'Mark Juz Completed',
    'mushaf_reader_progress_new_label': 'Select New Progress up to:',
    'mushaf_reader_save_progress_label': 'Save Progress',
    'mushaf_reader_juz_completed_banner': '✨ Alhamdulillah, this Juz has been completed!',
    'mushaf_reader_tap_instruction_banner': '💡 Tap the last ayah you read to update progress.',
    'mushaf_reader_no_program_title': 'No active program for Juz {juz}',
    'mushaf_reader_no_program_desc': 'Start a personal khataman or find a group to track reading progress for this Juz.',
    'mushaf_reader_btn_start_mandiri': 'Start Personal',
    'mushaf_reader_btn_find_group': 'Find Group',
    'mushaf_reader_switch_program_label': 'Select Program:',
    'mushaf_reader_btn_select_verse': 'Select Ayah',
    'mushaf_reader_dialog_select_verse_title': 'Select Progress Ayah',
    'mushaf_reader_select_verse_tip': 'Tip: You can also tap any verse text above directly to select.',
    'mushaf_reader_btn_apply': 'Apply',

    // Surah Info Screen
    'surah_info_title': 'Surah Info & Meaning',
    'surah_info_search_hint': 'Search surah (e.g., Al-Fatihah, The Opening...)',
    'surah_info_empty_search': 'Surah not found',

    // Surah Detail Screen
    'surah_detail_juz_place_verses': 'Surah No.{number} • {place} • {verses} Verses',
    'surah_detail_translation_label': 'Meaning: {translation}',
    'surah_detail_tab_meaning': 'Meaning & Significance',
    'surah_detail_tab_asbabun': 'Hadith & Asbab al-Nuzul',
    'surah_detail_tab_asbabun_sub': 'Why this surah was revealed',
    'surah_detail_tab_virtue': 'Impact & Virtues',
    'surah_detail_tab_virtue_sub': 'Benefits & rewards of recitation',

    // Active Khataman List Screen
    'active_list_title': 'Your Active Khataman',
    'active_list_empty_title': 'No Active Khataman Yet',
    'active_list_empty_body': 'Please create a personal progress or join a group progress first.',

    // Auth Screen
    'auth_login_failed': 'Login Failed: {error}',
    'auth_title': 'Khataman Quran',
    'auth_tagline': 'Track your spiritual journey\ntogether or alone.',
    'auth_privacy_notice': 'By signing in, you agree to our Terms of Service\nand Privacy Policy.',
    'auth_btn_login': 'Sign in with Google',
    'auth_tooltip_light_mode': 'Light Mode',
    'auth_tooltip_dark_mode': 'Dark Mode',

    // Additional Mandiri Screen keys (UI labels)
    'mandiri_appbar_title': 'Personal Progress',
    'mandiri_header_title': 'Khatam Progress',
    'mandiri_header_subtitle': 'Tap a juz to mark it as read',
    'mandiri_juz_label': 'Juz',
    'mandiri_completed_label': 'Completed',
    'mandiri_not_read_label': 'Not Read',
    // Group List & Detail & Assignment Screens
    'group_err_load': 'Failed to load data: {error}',
    'group_err_empty_name': 'Group name cannot be empty',
    'group_success_create': 'Group "{groupName}" successfully created! Code: {code}',
    'group_err_create': 'Failed to create group: {error}',
    'group_invite_title': 'Invite Members',
    'group_invite_subtitle': 'Choose friends to read Quran together',
    'group_search_user_hint': 'Search username or email...',
    'group_no_users': 'No other users',
    'group_no_match_users': 'No matching results',
    'group_btn_skip': 'Skip',
    'group_success_add_members': '{count} members successfully added!',
    'group_err_add_members_title': 'Failed to Add',
    'group_err_add_members_continue': 'Continue to Group',
    'group_err_add_members_body': 'Supabase Error: {error}\n\nMost likely the database (Row Level Security) prevents you from adding another person\'s account directly.',
    'group_badge_admin': 'Admin',
    'group_empty_my_groups': 'You haven\'t joined any groups yet.\nSearch for groups in the "All Groups" tab and click Join!',
    'group_empty_archived_groups': 'No archived groups yet.\nGroups will be archived after completing the Khatam Al-Quran prayer.',
    'group_btn_add': 'Add',
    'group_btn_add_count': 'Add ({count})',
    'group_someone': 'Someone',
    'group_notif_join_request_title': 'Join Request',
    'group_notif_join_request_body': '{user} requested to join group "{groupName}"',
    'group_notif_joined_title': 'New Member Joined',
    'group_notif_joined_body': '{user} has joined group "{groupName}"',
    'group_join_pending': 'Join request sent! Waiting for Admin approval.',
    'group_join_success': 'Successfully joined "{groupName}"!',
    'group_join_failed': 'Failed to join: already registered or error occurred',
    'group_join_cancel_success': 'Join request to "{groupName}" successfully cancelled.',
    'group_join_cancel_failed': 'Failed to cancel request: {error}',
    'group_join_cancel_dialog_title': 'Cancel Request?',
    'group_join_cancel_dialog_body': 'Are you sure you want to cancel your request to join group "{groupName}"?',
    'group_join_cancel_dialog_btn': 'Cancel Request',
    'group_tab_all': 'All Groups ({count})',
    'group_tab_my': 'My Groups ({count})',
    'group_tab_archived': 'Archive ({count})',
    'group_btn_create': 'Create Group',
    'group_create_dialog_title': 'Create New Group',
    'group_create_dialog_subtitle': 'Complete Al-Quran together',
    'group_create_field_name': 'Group Name',
    'group_create_field_name_hint': 'E.g., Family Khataman',
    'group_create_field_visibility': 'Group Visibility',
    'group_create_visibility_public': 'Public',
    'group_create_visibility_private': 'Private',
    'group_create_visibility_private_desc': 'Members must be approved by Admin before joining.',
    'group_create_field_type': 'Group Type',
    'group_create_type_insidental': 'Incidental',
    'group_create_type_rutin': 'Routine',
    'group_create_type_rutin_desc': 'Routine Type: Auto-rolling Juz rotation system cycles upon khatam.',
    'group_create_type_insidental_desc': 'Incidental Type: Juz allocations reset manually after khatam.',
    'group_create_btn_submit': 'Create Group Now',
    'group_search_hint': 'Search group or code...',
    'group_empty_search': 'No groups found',
    'group_badge_waiting': 'Pending',
    'group_badge_join': 'Join',
    'group_badge_open': 'Open',
    'group_admin_label': 'Admin: ',
    'group_admin_you': 'You',
    'group_progress_title': 'Group Progress',
    'group_progress_claimed': '{count} Claimed',
    'group_progress_completed': '{count} Completed ({percent}%)',
    'group_members_title': 'Group Members ',
    'group_members_count': '{count} People',
    'group_members_empty': 'No members yet.',
    'group_detail_out_by_admin': 'You have been removed from group "{groupName}" by admin.',
    'group_detail_celebration_title': 'Maa Syaa Allah! 🎉',
    'group_detail_celebration_alhamdulillah': 'Alhamdulillah',
    'group_detail_dialog_title_period': 'Select Khataman Period',
    'group_detail_btn_select': 'Select',
    'group_detail_btn_save': 'Save',
    'group_detail_err_roll_juz': 'Rolling Juz failed: {error}. Slots left empty.',
    'group_detail_notif_new_cycle_title': '📖 New Cycle Started!',
    'group_detail_notif_new_cycle_body': '{admin} started a new cycle in group "{groupName}" with deadline {date}.',
    'group_detail_start_new_cycle_title': 'Start New Cycle?',
    'group_detail_roll_method_title': 'Rolling Juz',
    'group_detail_roll_method_desc': 'Your group has completed this reading cycle.\n\nPlease choose a Juz assignment method for the next cycle:',
    'group_detail_roll_method_equal': 'Distribute Equally',
    'group_detail_roll_method_manual': 'Distribute Manually',
    'group_detail_roll_method_claim': 'Self Claim',
    'group_detail_err_slot_claimed': '⚠️ This Juz has been taken by another member. Choose another Juz.',
    'group_detail_success_slot_claimed': '✅ Juz successfully claimed!',
    'group_detail_err_claim_failed': 'Failed to claim Juz: {error}',
    'group_detail_direct_released_title': 'Juz Released by Admin 🚪',
    'group_detail_direct_released_body': '{user} has released Juz {juz} in group "{groupName}". This slot is now empty and open to claim!',
    'group_detail_direct_released_success': '✅ Juz successfully released and notification sent to member.',
    'group_detail_err_max_releases': '⚠️ Maximum of 2 concurrent Juz release requests allowed. Wait for admin response.',
    'group_detail_release_req_title': 'Juz Release Request 📖',
    'group_detail_release_req_body': '{user} requested to release Juz {juz} in group "{groupName}".',
    'group_detail_release_req_sent': '📤 Release request sent. Waiting for admin approval.',
    'group_detail_release_req_failed': 'Failed to request Juz release: {error}',
    'group_detail_release_req_cancelled': '↩️ Juz release request cancelled.',
    'group_detail_release_cancel_failed': 'Failed to cancel request: {error}',
    'group_detail_days_remaining': '{count} days remaining',
    'group_detail_hours_remaining': '{count} hours remaining',
    'group_detail_minutes_remaining': '{count} minutes remaining',
    'group_detail_seconds_remaining': 'Few seconds remaining',
    'group_detail_time_expired': 'Time expired',
    'group_detail_add_member_title': 'Add New Member',
    'group_detail_manage_member_title': 'Manage Members',
    'group_detail_add_member_subtitle': 'Search and add new members to group',
    'group_detail_manage_member_subtitle': 'Add new members or manage current ones',
    'group_detail_search_member_hint': 'Search username to add...',
    'group_detail_notif_added_title': 'Added to Khataman Group',
    'group_detail_notif_added_body': 'You have been added to group "{groupName}" by admin.',
    'group_detail_success_added_member': '{user} successfully added to group',
    'group_detail_err_added_member': 'Failed to add: {error}',
    'group_detail_search_empty_members': 'User not found or already in group.',
    'group_detail_search_start_prompt': 'Start searching username to add...',
    'group_detail_current_members_title': 'Current Members List',
    'group_detail_no_other_members': 'No other members in this group.',
    'group_detail_status_pending': 'Pending Approval',
    'group_detail_status_active': 'Active Member',
    'group_detail_btn_approve': 'Approve',
    'group_detail_notif_approved_title': 'Join Request Approved',
    'group_detail_notif_approved_body': 'Congratulations! Your request to join group "{groupName}" has been approved.',
    'group_detail_success_approved': '{user} successfully approved to join',
    'group_detail_err_approved': 'Failed to approve: Connection issue or try again ({error})',
    'group_detail_btn_reject': 'Reject',
    'group_detail_reject_dialog_title': 'Reject Request?',
    'group_detail_reject_dialog_body': 'Are you sure you want to reject join request from {user}?',
    'group_detail_success_rejected': 'Join request for {user} rejected',
    'group_detail_err_rejected': 'Failed to reject request: Connection issue or try again ({error})',
    'group_detail_priority_title': 'Priority quota share',
    'group_detail_priority_enabled': '⭐ {user} granted priority quota allocation!',
    'group_detail_priority_disabled': '⚪ Priority quota allocation for {user} disabled.',
    'group_detail_priority_failed': 'Failed to change priority: {error}',
    'group_detail_transfer_title': 'Transfer Admin',
    'group_detail_transfer_dialog_title': 'Transfer Admin?',
    'group_detail_transfer_dialog_body': 'Are you sure you want to transfer admin ownership to {user}?',
    'group_detail_transfer_confirm': 'Yes, Transfer',
    'group_detail_notif_transfer_title': 'Admin Promotion 👑',
    'group_detail_notif_transfer_body': 'You have been promoted to Admin for group "{groupName}" by previous admin.',
    'group_detail_success_transfer': 'Admin rights successfully transferred to {user}',
    'group_detail_err_transfer': 'Failed to transfer admin: {error}',
    'group_detail_kick_title': 'Remove Member',
    'group_detail_kick_dialog_title': 'Remove Member?',
    'group_detail_kick_dialog_body': 'Are you sure you want to remove {user} from group? All slot assignments for this user will be cleared.',
    'group_detail_kick_confirm': 'Remove',
    'group_detail_notif_kicked_title': 'Removed from Group 🚪',
    'group_detail_notif_kicked_body': 'You have been removed from group "{groupName}" by admin.',
    'group_detail_success_kicked': '{user} successfully removed from group',
    'group_detail_err_kicked': 'Failed to remove member: Connection issue or try again ({error})',
    'group_detail_err_load_members': 'Failed to load members: {error}',
    'group_detail_deadline_dialog_title': 'Select New Target Deadline',
    'group_detail_notif_deadline_title': '⏰ Group Deadline Updated',
    'group_detail_notif_deadline_body': '{admin} updated group "{groupName}" target deadline to {date}.',
    'group_detail_success_deadline': '✅ Target deadline successfully updated!',
    'group_detail_err_deadline': 'Failed to update deadline: {error}',
    'group_detail_settings_title': 'Group Settings',
    'group_detail_settings_share': 'Share Invitation Code',
    'group_detail_settings_type': 'Group Type',
    'group_detail_settings_type_rutin_desc': '🔁 ROUTINE: Endless cycling with automatic rolling Juz support',
    'group_detail_settings_type_insidental_desc': '⚡ INCIDENTAL: Single run, archives group upon completion',
    'group_detail_settings_type_success': 'Group type changed to {val}!',
    'group_detail_settings_type_failed': 'Failed to change group type: {error}',
    'group_detail_settings_limit': 'Limit Juz Claims',
    'group_detail_settings_limit_active': '🔒 Active: Max {count} Juz per member',
    'group_detail_settings_limit_inactive': '🔓 Free: Members can claim unlimited slots',
    'group_detail_settings_limit_rls': 'Update permission denied (RLS).',
    'group_detail_settings_limit_success_active': '🔒 Juz claim limit enabled!',
    'group_detail_settings_limit_success_inactive': '🔓 Juz claim limit disabled!',
    'group_detail_settings_limit_failed': 'Failed to change claim limit: {error}',
    'group_detail_settings_manage': 'Manage Members',
    'group_detail_settings_manage_desc': 'Approve join requests & add new members',
    'group_detail_settings_assign': 'Juz Assignment (Admin)',
    'group_detail_settings_deadline': 'Change Target Deadline',
    'group_detail_settings_deadline_desc': 'Extend or adjust target completion time',
    'group_detail_settings_history': 'Cycle History',
    'group_detail_settings_history_desc': 'View list of completed cycle history',
    'group_detail_settings_leave': 'Leave Group',
    'group_detail_settings_leave_desc': 'Leave group and transfer admin rights to someone else',
    'group_detail_settings_delete': 'Delete Group',
    'group_detail_settings_delete_desc': 'Permanently delete this group from server',
    'group_detail_settings_view_members': 'Members List',
    'group_detail_settings_view_members_desc': 'View current group members list',
    'group_detail_settings_leave_member_desc': 'Leave group and release all your claimed Juz slots',
    'group_detail_members_empty': 'No other members.',
    'group_detail_members_err': 'Failed to load members list: {error}',
    'group_detail_history_title': 'Khataman History',
    'group_detail_history_subtitle': 'Completed group cycles list',
    'group_detail_history_err': 'Failed to load history: {error}',
    'group_detail_history_empty_title': 'No History Yet',
    'group_detail_history_empty_body': 'Complete the 30 Juz target in the active cycle to record your group\'s first history!',
    'group_detail_history_great_achievement': 'Outstanding Achievement!',
    'group_detail_history_completed_count': 'Total {count} Khatams',
    'group_detail_history_blessing_text': 'May every verse read together bring blessing and consistency.',
    'group_detail_cycle_number': 'Cycle {number}',
    'group_detail_cycle_detail_err': 'Failed to load reader details or slot data not found.',
    'group_detail_cycle_detail_title': 'Readers List by Juz:',
    'group_detail_cycle_detail_free': 'General',
    'group_detail_cycle_detail_juz_user': 'Juz {juz}: @{user}',
    'group_detail_leave_dialog_title': 'Leave Group?',
    'group_detail_leave_dialog_body': 'Are you sure you want to leave this group? All your claimed Juz slots will be released.',
    'group_detail_leave_dialog_confirm': 'Leave',
    'group_detail_leave_success': 'You have left the group.',
    'group_detail_leave_failed': 'Failed to leave group: {error}',
    'group_detail_delete_dialog_title': 'Delete Group?',
    'group_detail_delete_dialog_body': 'This group and all progress will be permanently deleted. This action cannot be undone.',
    'group_detail_delete_confirm': 'Yes, Delete',
    'group_detail_notif_delete_title': 'Khataman Group Deleted 🗑️',
    'group_detail_notif_delete_body': 'Group "{groupName}" has been deleted by admin.',
    'group_detail_delete_failed': 'Failed to delete group. You might not have DB permissions (RLS).',
    'group_detail_delete_success': 'Group successfully deleted',
    'group_detail_delete_err_dialog_title': 'Failed to Delete Group',
    'group_detail_completed_count_badge': '🏆 {count} Khatam Cycles Completed!',
    'group_detail_view_history_link': 'View Full History ➔',
    'group_detail_join_code_label': 'Join Code',
    'group_detail_copied_link': 'Group invitation link copied! 🔗',
    'group_detail_copy_instruction': 'Long press to copy',
    'group_detail_share_title': 'Share Invitation Code',
    'group_detail_share_instruction': 'Long press to copy, or tap share icon to send invitation details.',
    'group_detail_members_count_label': 'Joined Members ({count})',
    'group_detail_settings_limit_active_badge': 'Juz Claim Limits: ACTIVE (Max {count} Juz)',
    'group_detail_settings_limit_inactive_badge': 'Juz Claim Limits: INACTIVE (Free)',
    'group_detail_roll_title_random': 'Rolling Juz (Smart Random)',
    'group_detail_roll_title_equal': 'Auto-Distribute Equally',
    'group_detail_roll_title_manual': 'Distribute Manually (Admin)',
    'group_detail_roll_title_claim': 'Self Claim (Open Slot)',
    'group_detail_confirm_cycle_complete_title': 'Confirm Cycle Completion',
    'group_detail_confirm_archive_title': 'Confirm Group Khataman',
    'group_detail_confirm_cycle_complete_desc': 'Upon confirmation, the current cycle will complete and be logged in history. You can then instantly start the next cycle.',
    'group_detail_confirm_archive_desc': 'Upon confirmation, this group will be archived and the khatam progress logged in history. Other members will be notified.',
    'group_detail_confirm_cycle_complete_instruction': 'This action will complete the current cycle and record it in group history. You can instantly start the next cycle. Continue?',
    'group_detail_confirm_archive_instruction': 'This action will complete the khatam progress, permanently archive this group, and log it in history for all members. Continue?',
    'group_detail_btn_doa': 'Not Yet, Read Doa',
    'group_detail_btn_yes': 'Yes, Finished',
    'group_detail_notif_cycle_complete_title': '🎉 Group Cycle Completed!',
    'group_detail_notif_archive_title': '📁 Khataman Archived',
    'group_detail_notif_cycle_complete_body': '"{groupName}" cycle completed by {user}. Alhamdulillah!',
    'group_detail_notif_archive_body': '"{groupName}" archived by {user} after finishing Doa Khatam. Alhamdulillah!',
    'group_detail_success_cycle_complete': '🎉 Group cycle successfully completed!',
    'group_detail_success_archive': '📁 Group archived. Alhamdulillah!',
    'group_detail_err_cycle_complete': 'Failed to complete cycle: {error}',
    'group_detail_cycle_title': 'Cycle {number}',
    'group_detail_unlimited_juz': 'Claim unlimited Juz',
    'group_detail_celebration_alhamdulillah_desc': 'Alhamdulillah! Group "{groupName}" has completed the 30 Juz Al-Quran cycle.',
    'group_detail_btn_new_cycle': 'New Cycle',
    'group_detail_archived_banner': 'This group has been archived. Khatam progress logged in history.',
    'group_detail_transfer_single_member': 'You are the Admin of group "{groupName}". Select an active member to replace your leadership before leaving:',
    'group_detail_btn_confirm_continue': 'Confirm & Continue',
    'group_detail_kick_only_member_title': 'Leave & Delete Group?',
    'group_detail_kick_only_member_body': 'You are the only member in this group. If you leave, the group will be permanently deleted. Continue?',
    'group_detail_kick_only_member_confirm': 'Leave & Delete',
    'group_detail_success_transfer_leave': 'Successfully transferred admin and left the group.',
    'group_detail_err_transfer_leave': 'Failed to leave group: {error}',

    // Juz Assignment Screen
    'juz_assign_title': 'Juz Assignment',
    'juz_assign_notif_release_req_title': 'Juz Release Approval',
    'juz_assign_notif_release_req_body': 'Member "{user}" requested to release Juz {juz}.',
    'juz_assign_success_release': 'Juz {juz} successfully released.',
    'juz_assign_err_approve': 'Failed to approve: {error}',
    'juz_assign_err_reject': 'Failed to reject: {error}',
    'juz_assign_success_reject': 'Release request for Juz {juz} rejected.',
    'juz_assign_err_limit_exceeded': 'Failed! This member has reached the max share limit ({limit} Juz).',
    'juz_assign_transfer_title': 'Transfer Juz Assignment?',
    'juz_assign_transfer_body': 'This Juz is already assigned but NOT yet read. Are you sure you want to transfer it?',
    'juz_assign_transfer_no': 'No',
    'juz_assign_transfer_yes': 'Yes, Transfer',
    'juz_assign_progress_exists_title': 'Juz Already Read!',
    'juz_assign_progress_exists_body': 'Juz {juz} has reading progress. Are you sure you want to force change or delete its assignment? This will reset the reading progress for this Juz.',
    'juz_assign_progress_exists_yes': 'Yes, Force Change',
    'juz_assign_confirm_save_title': 'Save Changes?',
    'juz_assign_confirm_save_body': 'You have unsaved Juz assignment drafts. Do you want to save these changes?',
    'juz_assign_confirm_save_discard': 'Discard',
    'juz_assign_confirm_save_success': '✅ Juz assignments successfully saved!',
    'juz_assign_brush_eraser': 'Eraser',
    'juz_assign_brush_info_delete': 'Eraser active! Tap a Juz box to clear its assignment.',
    'juz_assign_brush_info_draw': 'Brush active! Tap a Juz box to allocate directly.',
    'juz_assign_empty_cycle': 'No active cycle',
    'juz_assign_empty_cycle_desc': 'Start a new cycle first.',
    'juz_assign_btn_reset': 'Reset Changes',
    'juz_assign_success_reset': 'Unsaved assignment drafts cleared successfully',
    'juz_assign_btn_clear_all': 'Clear All',
    'juz_assign_brush_members': '🎨 Member Brush',

  }
};

extension LocalizationContext on BuildContext {
  String translate(String key) {
    final settings = Provider.of<SettingsProvider>(this, listen: false);
    final lang = settings.language;
    return localizedStrings[lang]?[key] ?? key;
  }
}
